# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.48.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.evaluate_policies_batch_response import EvaluatePoliciesBatchResponse

class TestEvaluatePoliciesBatchResponse(unittest.TestCase):
    """EvaluatePoliciesBatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvaluatePoliciesBatchResponse:
        """Test EvaluatePoliciesBatchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvaluatePoliciesBatchResponse`
        """
        model = EvaluatePoliciesBatchResponse()
        if include_optional:
            return EvaluatePoliciesBatchResponse(
                results = [
                    tachyon_sdk.models.policy_evaluation_outcome.PolicyEvaluationOutcome(
                        action = '', 
                        allowed = True, 
                        error = '', )
                    ]
            )
        else:
            return EvaluatePoliciesBatchResponse(
                results = [
                    tachyon_sdk.models.policy_evaluation_outcome.PolicyEvaluationOutcome(
                        action = '', 
                        allowed = True, 
                        error = '', )
                    ],
        )
        """

    def testEvaluatePoliciesBatchResponse(self):
        """Test EvaluatePoliciesBatchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
