# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.48.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.update_product_variation_request import UpdateProductVariationRequest

class TestUpdateProductVariationRequest(unittest.TestCase):
    """UpdateProductVariationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateProductVariationRequest:
        """Test UpdateProductVariationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateProductVariationRequest`
        """
        model = UpdateProductVariationRequest()
        if include_optional:
            return UpdateProductVariationRequest(
                code = '',
                currency = '',
                id = '',
                metadata = None,
                name = '',
                publication_description = '',
                publication_name = '',
                recurring = '',
                status = '',
                unit_amount = 56
            )
        else:
            return UpdateProductVariationRequest(
                id = '',
        )
        """

    def testUpdateProductVariationRequest(self):
        """Test UpdateProductVariationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
