# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.51.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.agent_chunk_event_one_of10 import AgentChunkEventOneOf10

class TestAgentChunkEventOneOf10(unittest.TestCase):
    """AgentChunkEventOneOf10 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentChunkEventOneOf10:
        """Test AgentChunkEventOneOf10
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentChunkEventOneOf10`
        """
        model = AgentChunkEventOneOf10()
        if include_optional:
            return AgentChunkEventOneOf10(
                job_id = '',
                provider = '',
                tool_id = '',
                type = 'tool_job_started'
            )
        else:
            return AgentChunkEventOneOf10(
                job_id = '',
                provider = '',
                tool_id = '',
                type = 'tool_job_started',
        )
        """

    def testAgentChunkEventOneOf10(self):
        """Test AgentChunkEventOneOf10"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
