# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.49.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.tool_choice import ToolChoice

class TestToolChoice(unittest.TestCase):
    """ToolChoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToolChoice(self):
        """Test ToolChoice"""
        # inst = ToolChoice()

if __name__ == '__main__':
    unittest.main()
