# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.49.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.delta_message import DeltaMessage

class TestDeltaMessage(unittest.TestCase):
    """DeltaMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeltaMessage:
        """Test DeltaMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeltaMessage`
        """
        model = DeltaMessage()
        if include_optional:
            return DeltaMessage(
                content = '',
                role = 'system',
                tool_calls = [
                    tachyon_sdk.models.tool_call.ToolCall(
                        tool_id = '', 
                        tool_name = '', )
                    ]
            )
        else:
            return DeltaMessage(
        )
        """

    def testDeltaMessage(self):
        """Test DeltaMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
