# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.49.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.client_list_response import ClientListResponse

class TestClientListResponse(unittest.TestCase):
    """ClientListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientListResponse:
        """Test ClientListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientListResponse`
        """
        model = ClientListResponse()
        if include_optional:
            return ClientListResponse(
                items = [
                    tachyon_sdk.models.client_response.ClientResponse(
                        capital = 0, 
                        corporate_number = '', 
                        email = '', 
                        fax_number = '', 
                        founded = '', 
                        head_office_address = null, 
                        id = '', 
                        industry = '', 
                        listed = True, 
                        name = '', 
                        phone_number = '', 
                        representative = '', 
                        tenant_id = '', )
                    ]
            )
        else:
            return ClientListResponse(
                items = [
                    tachyon_sdk.models.client_response.ClientResponse(
                        capital = 0, 
                        corporate_number = '', 
                        email = '', 
                        fax_number = '', 
                        founded = '', 
                        head_office_address = null, 
                        id = '', 
                        industry = '', 
                        listed = True, 
                        name = '', 
                        phone_number = '', 
                        representative = '', 
                        tenant_id = '', )
                    ],
        )
        """

    def testClientListResponse(self):
        """Test ClientListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
