# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.58.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.api.notifications_api import NotificationsApi
from tachyon_sdk.models.send_sms_notification_request import SendSmsNotificationRequest


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit tests"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_send_sms_notification(self) -> None:
        """Serializes SMS notification endpoint, headers, and payload."""
        request = SendSmsNotificationRequest(
            phone_number="+15551234567",
            message="Your verification code is 123456.",
        )

        method, url, headers, body, post_params = self.api._send_sms_notification_serialize(
            x_operator_id="tn_test",
            authorization="Bearer test-token",
            send_sms_notification_request=request,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0,
        )

        self.assertEqual(method, "POST")
        self.assertTrue(url.endswith("/v1/notifications/sms"))
        self.assertEqual(headers["x-operator-id"], "tn_test")
        self.assertEqual(headers["Authorization"], "Bearer test-token")
        self.assertEqual(headers["Content-Type"], "application/json")
        self.assertEqual(
            body,
            {
                "phoneNumber": "+15551234567",
                "message": "Your verification code is 123456.",
            },
        )
        self.assertEqual(post_params, [])


if __name__ == '__main__':
    unittest.main()
