# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.49.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.agent_chunk_event_one_of import AgentChunkEventOneOf

class TestAgentChunkEventOneOf(unittest.TestCase):
    """AgentChunkEventOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentChunkEventOneOf:
        """Test AgentChunkEventOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentChunkEventOneOf`
        """
        model = AgentChunkEventOneOf()
        if include_optional:
            return AgentChunkEventOneOf(
                tool_id = '',
                tool_name = '',
                type = 'tool_call'
            )
        else:
            return AgentChunkEventOneOf(
                tool_id = '',
                tool_name = '',
                type = 'tool_call',
        )
        """

    def testAgentChunkEventOneOf(self):
        """Test AgentChunkEventOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
