# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.58.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.create_operator_response import CreateOperatorResponse

class TestCreateOperatorResponse(unittest.TestCase):
    """CreateOperatorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOperatorResponse:
        """Test CreateOperatorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOperatorResponse`
        """
        model = CreateOperatorResponse()
        if include_optional:
            return CreateOperatorResponse(
                operator = tachyon_sdk.models.operator_response.OperatorResponse(
                    id = '', 
                    name = '', 
                    operator_name = '', 
                    platform_id = '', ),
                owner_id = ''
            )
        else:
            return CreateOperatorResponse(
                operator = tachyon_sdk.models.operator_response.OperatorResponse(
                    id = '', 
                    name = '', 
                    operator_name = '', 
                    platform_id = '', ),
                owner_id = '',
        )
        """

    def testCreateOperatorResponse(self):
        """Test CreateOperatorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
