# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.48.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.offset_paginator import OffsetPaginator

class TestOffsetPaginator(unittest.TestCase):
    """OffsetPaginator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OffsetPaginator:
        """Test OffsetPaginator
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OffsetPaginator`
        """
        model = OffsetPaginator()
        if include_optional:
            return OffsetPaginator(
                current_page = 0,
                items_per_page = 0,
                total_items = 0,
                total_pages = 0
            )
        else:
            return OffsetPaginator(
                current_page = 0,
                items_per_page = 0,
                total_items = 0,
                total_pages = 0,
        )
        """

    def testOffsetPaginator(self):
        """Test OffsetPaginator"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
