# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.48.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.api_key_response import ApiKeyResponse

class TestApiKeyResponse(unittest.TestCase):
    """ApiKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyResponse:
        """Test ApiKeyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyResponse`
        """
        model = ApiKeyResponse()
        if include_optional:
            return ApiKeyResponse(
                created_at = '',
                id = '',
                name = '',
                service_account_id = '',
                value = ''
            )
        else:
            return ApiKeyResponse(
                created_at = '',
                id = '',
                name = '',
                service_account_id = '',
                value = '',
        )
        """

    def testApiKeyResponse(self):
        """Test ApiKeyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
