# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.48.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.api.auth_service_accounts_api import AuthServiceAccountsApi


class TestAuthServiceAccountsApi(unittest.TestCase):
    """AuthServiceAccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthServiceAccountsApi()

    def tearDown(self) -> None:
        pass

    def test_create_service_account(self) -> None:
        """Test case for create_service_account

        Create a new service account
        """
        pass

    def test_delete_service_account(self) -> None:
        """Test case for delete_service_account

        Delete a service account
        """
        pass

    def test_get_service_account(self) -> None:
        """Test case for get_service_account

        Get a service account by ID
        """
        pass

    def test_list_service_accounts(self) -> None:
        """Test case for list_service_accounts

        List all service accounts
        """
        pass

    def test_update_service_account(self) -> None:
        """Test case for update_service_account

        Update a service account
        """
        pass


if __name__ == '__main__':
    unittest.main()
