# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.58.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.consent_response import ConsentResponse

class TestConsentResponse(unittest.TestCase):
    """ConsentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConsentResponse:
        """Test ConsentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConsentResponse`
        """
        model = ConsentResponse()
        if include_optional:
            return ConsentResponse(
                client_id = '',
                client_name = '',
                consent_id = '',
                consented_at = '',
                granted_scopes = [
                    ''
                    ],
                revoked_at = ''
            )
        else:
            return ConsentResponse(
                client_id = '',
                client_name = '',
                consent_id = '',
                consented_at = '',
                granted_scopes = [
                    ''
                    ],
        )
        """

    def testConsentResponse(self):
        """Test ConsentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
