# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.51.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.api.auth_o_auth_tokens_api import AuthOAuthTokensApi


class TestAuthOAuthTokensApi(unittest.TestCase):
    """AuthOAuthTokensApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthOAuthTokensApi()

    def tearDown(self) -> None:
        pass

    def test_delete_oauth_token(self) -> None:
        """Test case for delete_oauth_token

        Delete an OAuth token
        """
        pass

    def test_get_oauth_token_by_provider(self) -> None:
        """Test case for get_oauth_token_by_provider

        Get an OAuth token by provider
        """
        pass

    def test_list_oauth_tokens(self) -> None:
        """Test case for list_oauth_tokens

        List all OAuth tokens
        """
        pass

    def test_save_oauth_token(self) -> None:
        """Test case for save_oauth_token

        Save an OAuth token
        """
        pass


if __name__ == '__main__':
    unittest.main()
