# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.58.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.register_policy_request import RegisterPolicyRequest

class TestRegisterPolicyRequest(unittest.TestCase):
    """RegisterPolicyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisterPolicyRequest:
        """Test RegisterPolicyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisterPolicyRequest`
        """
        model = RegisterPolicyRequest()
        if include_optional:
            return RegisterPolicyRequest(
                action_patterns = [
                    tachyon_sdk.models.policy_action_pattern_request.PolicyActionPatternRequest(
                        context_pattern = '', 
                        effect = '', 
                        name_pattern = '', )
                    ],
                actions = [
                    tachyon_sdk.models.policy_action_request.PolicyActionRequest(
                        action_full_name = '', 
                        effect = '', )
                    ],
                description = '',
                var_global = True,
                is_system = True,
                name = '',
                tenant_id = ''
            )
        else:
            return RegisterPolicyRequest(
                name = '',
        )
        """

    def testRegisterPolicyRequest(self):
        """Test RegisterPolicyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
