# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.49.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.variant_link_response import VariantLinkResponse

class TestVariantLinkResponse(unittest.TestCase):
    """VariantLinkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantLinkResponse:
        """Test VariantLinkResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariantLinkResponse`
        """
        model = VariantLinkResponse()
        if include_optional:
            return VariantLinkResponse(
                id = '',
                metadata = None,
                procurement_code = '',
                supplier_id = '',
                tenant_id = '',
                variant_id = ''
            )
        else:
            return VariantLinkResponse(
                id = '',
                metadata = None,
                procurement_code = '',
                supplier_id = '',
                tenant_id = '',
                variant_id = '',
        )
        """

    def testVariantLinkResponse(self):
        """Test VariantLinkResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
