# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.48.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.api.order_quotes_api import OrderQuotesApi


class TestOrderQuotesApi(unittest.TestCase):
    """OrderQuotesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrderQuotesApi()

    def tearDown(self) -> None:
        pass

    def test_create_quote(self) -> None:
        """Test case for create_quote

        Create a new quote
        """
        pass

    def test_get_quote(self) -> None:
        """Test case for get_quote

        Get a quote by ID
        """
        pass

    def test_issue_quote(self) -> None:
        """Test case for issue_quote

        Issue a quote to a client
        """
        pass

    def test_list_quotes(self) -> None:
        """Test case for list_quotes

        List all quotes
        """
        pass


if __name__ == '__main__':
    unittest.main()
