# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.48.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.api.order_clients_api import OrderClientsApi


class TestOrderClientsApi(unittest.TestCase):
    """OrderClientsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrderClientsApi()

    def tearDown(self) -> None:
        pass

    def test_create_client(self) -> None:
        """Test case for create_client

        Create a new client
        """
        pass

    def test_get_client(self) -> None:
        """Test case for get_client

        Get a client by ID
        """
        pass

    def test_list_clients(self) -> None:
        """Test case for list_clients

        List all clients
        """
        pass


if __name__ == '__main__':
    unittest.main()
