# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.49.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.api.models_api import ModelsApi


class TestModelsApi(unittest.TestCase):
    """ModelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModelsApi()

    def tearDown(self) -> None:
        pass

    def test_get_models(self) -> None:
        """Test case for get_models

        Get list of supported models
        """
        pass


if __name__ == '__main__':
    unittest.main()
