# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.58.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.api.auth_operators_api import AuthOperatorsApi


class TestAuthOperatorsApi(unittest.TestCase):
    """AuthOperatorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthOperatorsApi()

    def tearDown(self) -> None:
        pass

    def test_create_operator(self) -> None:
        """Test case for create_operator

        Create an operator under a platform
        """
        pass

    def test_find_operators_by_user(self) -> None:
        """Test case for find_operators_by_user

        Find operators accessible to a user under a platform
        """
        pass

    def test_get_operator_by_alias(self) -> None:
        """Test case for get_operator_by_alias

        Get an operator by alias within a platform
        """
        pass

    def test_get_operator_by_id(self) -> None:
        """Test case for get_operator_by_id

        Get an operator by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
