# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.48.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.chat_role import ChatRole

class TestChatRole(unittest.TestCase):
    """ChatRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChatRole(self):
        """Test ChatRole"""
        # inst = ChatRole()

if __name__ == '__main__':
    unittest.main()
