# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.49.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.billing_address_request import BillingAddressRequest

class TestBillingAddressRequest(unittest.TestCase):
    """BillingAddressRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingAddressRequest:
        """Test BillingAddressRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingAddressRequest`
        """
        model = BillingAddressRequest()
        if include_optional:
            return BillingAddressRequest(
                city = '',
                country = '',
                line1 = '',
                line2 = '',
                postal_code = '',
                state = ''
            )
        else:
            return BillingAddressRequest(
        )
        """

    def testBillingAddressRequest(self):
        """Test BillingAddressRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
