# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.49.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.product_list_response import ProductListResponse

class TestProductListResponse(unittest.TestCase):
    """ProductListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductListResponse:
        """Test ProductListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductListResponse`
        """
        model = ProductListResponse()
        if include_optional:
            return ProductListResponse(
                has_next_page = True,
                items = [
                    tachyon_sdk.models.product_response.ProductResponse(
                        billing_cycle = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        id = '', 
                        image_file_ids = [
                            ''
                            ], 
                        jan_code = '', 
                        kind = '', 
                        list_price = 0, 
                        name = '', 
                        publication_description = '', 
                        publication_name = '', 
                        publication_status = '', 
                        sku_code = '', 
                        status = '', 
                        tenant_id = '', 
                        upc_code = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                limit = 56,
                offset = 56,
                total_count = 0
            )
        else:
            return ProductListResponse(
                has_next_page = True,
                items = [
                    tachyon_sdk.models.product_response.ProductResponse(
                        billing_cycle = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        id = '', 
                        image_file_ids = [
                            ''
                            ], 
                        jan_code = '', 
                        kind = '', 
                        list_price = 0, 
                        name = '', 
                        publication_description = '', 
                        publication_name = '', 
                        publication_status = '', 
                        sku_code = '', 
                        status = '', 
                        tenant_id = '', 
                        upc_code = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                limit = 56,
                offset = 56,
                total_count = 0,
        )
        """

    def testProductListResponse(self):
        """Test ProductListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
