# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.58.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tachyon_sdk.models.remove_policy_action_pattern_request import RemovePolicyActionPatternRequest

class TestRemovePolicyActionPatternRequest(unittest.TestCase):
    """RemovePolicyActionPatternRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemovePolicyActionPatternRequest:
        """Test RemovePolicyActionPatternRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemovePolicyActionPatternRequest`
        """
        model = RemovePolicyActionPatternRequest()
        if include_optional:
            return RemovePolicyActionPatternRequest(
                context_pattern = '',
                name_pattern = ''
            )
        else:
            return RemovePolicyActionPatternRequest(
                context_pattern = '',
                name_pattern = '',
        )
        """

    def testRemovePolicyActionPatternRequest(self):
        """Test RemovePolicyActionPatternRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
