# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.49.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from tachyon_sdk.models.line_item_response import LineItemResponse
from typing import Optional, Set
from typing_extensions import Self

class QuoteResponse(BaseModel):
    """
    Quote response
    """ # noqa: E501
    client_id: Optional[StrictStr] = Field(default=None, description="Client ID", alias="clientId")
    created_at: datetime = Field(description="Created at", alias="createdAt")
    currency: StrictStr = Field(description="Transaction currency")
    id: StrictStr = Field(description="Quote ID")
    line_items: List[LineItemResponse] = Field(description="Line items", alias="lineItems")
    order_date: StrictStr = Field(description="Order date", alias="orderDate")
    software_tenant_id: Optional[StrictStr] = Field(default=None, description="Software tenant ID", alias="softwareTenantId")
    status: StrictStr = Field(description="Quote status")
    subtotal: Union[StrictFloat, StrictInt] = Field(description="Subtotal")
    tax: Annotated[int, Field(strict=True, ge=0)] = Field(description="Tax percentage")
    tenant_id: StrictStr = Field(description="Tenant ID", alias="tenantId")
    title: StrictStr = Field(description="Quote title")
    total: Union[StrictFloat, StrictInt] = Field(description="Total amount")
    updated_at: datetime = Field(description="Updated at", alias="updatedAt")
    url: Optional[StrictStr] = Field(default=None, description="Quote URL")
    __properties: ClassVar[List[str]] = ["clientId", "createdAt", "currency", "id", "lineItems", "orderDate", "softwareTenantId", "status", "subtotal", "tax", "tenantId", "title", "total", "updatedAt", "url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuoteResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in line_items (list)
        _items = []
        if self.line_items:
            for _item_line_items in self.line_items:
                if _item_line_items:
                    _items.append(_item_line_items.to_dict())
            _dict['lineItems'] = _items
        # set to None if client_id (nullable) is None
        # and model_fields_set contains the field
        if self.client_id is None and "client_id" in self.model_fields_set:
            _dict['clientId'] = None

        # set to None if software_tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.software_tenant_id is None and "software_tenant_id" in self.model_fields_set:
            _dict['softwareTenantId'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuoteResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clientId": obj.get("clientId"),
            "createdAt": obj.get("createdAt"),
            "currency": obj.get("currency"),
            "id": obj.get("id"),
            "lineItems": [LineItemResponse.from_dict(_item) for _item in obj["lineItems"]] if obj.get("lineItems") is not None else None,
            "orderDate": obj.get("orderDate"),
            "softwareTenantId": obj.get("softwareTenantId"),
            "status": obj.get("status"),
            "subtotal": obj.get("subtotal"),
            "tax": obj.get("tax"),
            "tenantId": obj.get("tenantId"),
            "title": obj.get("title"),
            "total": obj.get("total"),
            "updatedAt": obj.get("updatedAt"),
            "url": obj.get("url")
        })
        return _obj


