# coding: utf-8

"""
    Tachyon API

    Tachyon Platform REST API

    The version of the OpenAPI document: 0.49.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class RecurringRevenueResponse(BaseModel):
    """
    Recurring revenue response
    """ # noqa: E501
    amount: Union[StrictFloat, StrictInt] = Field(description="Revenue amount")
    change_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Change percentage from previous period", alias="changePercentage")
    created_at: datetime = Field(description="Created at", alias="createdAt")
    cycle: StrictStr = Field(description="Revenue cycle")
    end_date: StrictStr = Field(description="Period end date", alias="endDate")
    id: StrictStr = Field(description="Revenue ID")
    start_date: StrictStr = Field(description="Period start date", alias="startDate")
    tenant_id: StrictStr = Field(description="Tenant ID", alias="tenantId")
    __properties: ClassVar[List[str]] = ["amount", "changePercentage", "createdAt", "cycle", "endDate", "id", "startDate", "tenantId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecurringRevenueResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if change_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.change_percentage is None and "change_percentage" in self.model_fields_set:
            _dict['changePercentage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecurringRevenueResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "changePercentage": obj.get("changePercentage"),
            "createdAt": obj.get("createdAt"),
            "cycle": obj.get("cycle"),
            "endDate": obj.get("endDate"),
            "id": obj.get("id"),
            "startDate": obj.get("startDate"),
            "tenantId": obj.get("tenantId")
        })
        return _obj


