/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`attach_user_policy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttachUserPolicyError {
    Status400(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`attach_user_policy_with_scope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttachUserPolicyWithScopeError {
    Status400(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`detach_user_policy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DetachUserPolicyError {
    Status400(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`detach_user_policy_with_scope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DetachUserPolicyWithScopeError {
    Status400(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`find_user_policy_mappings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FindUserPolicyMappingsError {
    Status400(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_user_policies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListUserPoliciesError {
    Status403(),
    UnknownValue(serde_json::Value),
}

pub async fn attach_user_policy(
    configuration: &configuration::Configuration,
    attach_user_policy_request: models::AttachUserPolicyRequest,
) -> Result<(), Error<AttachUserPolicyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_attach_user_policy_request = attach_user_policy_request;

    let uri_str =
        format!("{}/v1/auth/user-policies/attach", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder
            .header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_attach_user_policy_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AttachUserPolicyError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn attach_user_policy_with_scope(
    configuration: &configuration::Configuration,
    attach_user_policy_with_scope_request: models::AttachUserPolicyWithScopeRequest,
) -> Result<(), Error<AttachUserPolicyWithScopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_attach_user_policy_with_scope_request =
        attach_user_policy_with_scope_request;

    let uri_str = format!(
        "{}/v1/auth/user-policies/attach-with-scope",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder
            .header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder =
        req_builder.json(&p_body_attach_user_policy_with_scope_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AttachUserPolicyWithScopeError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn detach_user_policy(
    configuration: &configuration::Configuration,
    detach_user_policy_request: models::DetachUserPolicyRequest,
) -> Result<(), Error<DetachUserPolicyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_detach_user_policy_request = detach_user_policy_request;

    let uri_str =
        format!("{}/v1/auth/user-policies/detach", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder
            .header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_detach_user_policy_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DetachUserPolicyError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn detach_user_policy_with_scope(
    configuration: &configuration::Configuration,
    detach_user_policy_with_scope_request: models::DetachUserPolicyWithScopeRequest,
) -> Result<(), Error<DetachUserPolicyWithScopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_detach_user_policy_with_scope_request =
        detach_user_policy_with_scope_request;

    let uri_str = format!(
        "{}/v1/auth/user-policies/detach-with-scope",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder
            .header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder =
        req_builder.json(&p_body_detach_user_policy_with_scope_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DetachUserPolicyWithScopeError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn find_user_policy_mappings(
    configuration: &configuration::Configuration,
    tenant_id: &str,
    resource_scope: &str,
) -> Result<
    models::UserPolicyMappingListResponse,
    Error<FindUserPolicyMappingsError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_tenant_id = tenant_id;
    let p_query_resource_scope = resource_scope;

    let uri_str =
        format!("{}/v1/auth/user-policy-mappings", configuration.base_path);
    let mut req_builder =
        configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder =
        req_builder.query(&[("tenantId", &p_query_tenant_id.to_string())]);
    req_builder = req_builder
        .query(&[("resourceScope", &p_query_resource_scope.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder
            .header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UserPolicyMappingListResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UserPolicyMappingListResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FindUserPolicyMappingsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn list_user_policies(
    configuration: &configuration::Configuration,
    user_id: &str,
    tenant_id: Option<&str>,
) -> Result<models::UserPolicyListResponse, Error<ListUserPoliciesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;
    let p_query_tenant_id = tenant_id;

    let uri_str = format!(
        "{}/v1/auth/users/{user_id}/policies",
        configuration.base_path,
        user_id = crate::apis::urlencode(p_path_user_id)
    );
    let mut req_builder =
        configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_tenant_id {
        req_builder =
            req_builder.query(&[("tenantId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder
            .header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UserPolicyListResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UserPolicyListResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListUserPoliciesError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
