/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Evaluation result for each action
 * @export
 * @interface ActionEvaluationResult
 */
export interface ActionEvaluationResult {
    /**
     * Target action
     * @type {string}
     * @memberof ActionEvaluationResult
     */
    action: string;
    /**
     * Context used for evaluation (tenant info, etc.)
     * @type {string}
     * @memberof ActionEvaluationResult
     */
    context: string;
    /**
     * Whether Feature Flag is enabled
     * @type {boolean}
     * @memberof ActionEvaluationResult
     */
    featureEnabled: boolean;
    /**
     * Error message during Feature Flag evaluation
     * @type {string}
     * @memberof ActionEvaluationResult
     */
    featureError?: string | null;
    /**
     * Whether allowed by Policy
     * @type {boolean}
     * @memberof ActionEvaluationResult
     */
    policyAllowed: boolean;
    /**
     * Error message during Policy evaluation
     * @type {string}
     * @memberof ActionEvaluationResult
     */
    policyError?: string | null;
}

/**
 * Check if a given object implements the ActionEvaluationResult interface.
 */
export function instanceOfActionEvaluationResult(value: object): value is ActionEvaluationResult {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('featureEnabled' in value) || value['featureEnabled'] === undefined) return false;
    if (!('policyAllowed' in value) || value['policyAllowed'] === undefined) return false;
    return true;
}

export function ActionEvaluationResultFromJSON(json: any): ActionEvaluationResult {
    return ActionEvaluationResultFromJSONTyped(json, false);
}

export function ActionEvaluationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionEvaluationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'context': json['context'],
        'featureEnabled': json['featureEnabled'],
        'featureError': json['featureError'] == null ? undefined : json['featureError'],
        'policyAllowed': json['policyAllowed'],
        'policyError': json['policyError'] == null ? undefined : json['policyError'],
    };
}

export function ActionEvaluationResultToJSON(json: any): ActionEvaluationResult {
    return ActionEvaluationResultToJSONTyped(json, false);
}

export function ActionEvaluationResultToJSONTyped(value?: ActionEvaluationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'context': value['context'],
        'featureEnabled': value['featureEnabled'],
        'featureError': value['featureError'],
        'policyAllowed': value['policyAllowed'],
        'policyError': value['policyError'],
    };
}

