/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request DTO for adding a user to a tenant
 * @export
 * @interface AddUserToTenantRequest
 */
export interface AddUserToTenantRequest {
    /**
     * 
     * @type {string}
     * @memberof AddUserToTenantRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the AddUserToTenantRequest interface.
 */
export function instanceOfAddUserToTenantRequest(value: object): value is AddUserToTenantRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function AddUserToTenantRequestFromJSON(json: any): AddUserToTenantRequest {
    return AddUserToTenantRequestFromJSONTyped(json, false);
}

export function AddUserToTenantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserToTenantRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tenantId': json['tenantId'],
    };
}

export function AddUserToTenantRequestToJSON(json: any): AddUserToTenantRequest {
    return AddUserToTenantRequestToJSONTyped(json, false);
}

export function AddUserToTenantRequestToJSONTyped(value?: AddUserToTenantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenantId': value['tenantId'],
    };
}

