/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Single session entry in the list response.
 * @export
 * @interface AgentSessionEntry
 */
export interface AgentSessionEntry {
    /**
     * 
     * @type {Date}
     * @memberof AgentSessionEntry
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionEntry
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionEntry
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AgentSessionEntry
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the AgentSessionEntry interface.
 */
export function instanceOfAgentSessionEntry(value: object): value is AgentSessionEntry {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AgentSessionEntryFromJSON(json: any): AgentSessionEntry {
    return AgentSessionEntryFromJSONTyped(json, false);
}

export function AgentSessionEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentSessionEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function AgentSessionEntryToJSON(json: any): AgentSessionEntry {
    return AgentSessionEntryToJSONTyped(json, false);
}

export function AgentSessionEntryToJSONTyped(value?: AgentSessionEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'name': value['name'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

