/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Tool execution result
 * @export
 * @interface AgentChunkEventOneOf2
 */
export interface AgentChunkEventOneOf2 {
    /**
     * 
     * @type {boolean}
     * @memberof AgentChunkEventOneOf2
     */
    isFinished: boolean;
    /**
     * 
     * @type {string}
     * @memberof AgentChunkEventOneOf2
     */
    result: string;
    /**
     * 
     * @type {string}
     * @memberof AgentChunkEventOneOf2
     */
    toolId: string;
    /**
     * 
     * @type {AgentChunkEventOneOf2TypeEnum}
     * @memberof AgentChunkEventOneOf2
     */
    type: AgentChunkEventOneOf2TypeEnum;
}


/**
 * @export
 */
export const AgentChunkEventOneOf2TypeEnum = {
    ToolResult: 'tool_result'
} as const;
export type AgentChunkEventOneOf2TypeEnum = typeof AgentChunkEventOneOf2TypeEnum[keyof typeof AgentChunkEventOneOf2TypeEnum];


/**
 * Check if a given object implements the AgentChunkEventOneOf2 interface.
 */
export function instanceOfAgentChunkEventOneOf2(value: object): value is AgentChunkEventOneOf2 {
    if (!('isFinished' in value) || value['isFinished'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('toolId' in value) || value['toolId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AgentChunkEventOneOf2FromJSON(json: any): AgentChunkEventOneOf2 {
    return AgentChunkEventOneOf2FromJSONTyped(json, false);
}

export function AgentChunkEventOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentChunkEventOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'isFinished': json['is_finished'],
        'result': json['result'],
        'toolId': json['tool_id'],
        'type': json['type'],
    };
}

export function AgentChunkEventOneOf2ToJSON(json: any): AgentChunkEventOneOf2 {
    return AgentChunkEventOneOf2ToJSONTyped(json, false);
}

export function AgentChunkEventOneOf2ToJSONTyped(value?: AgentChunkEventOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_finished': value['isFinished'],
        'result': value['result'],
        'tool_id': value['toolId'],
        'type': value['type'],
    };
}

