/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Task completion attempt
 * @export
 * @interface AgentChunkEventOneOf8
 */
export interface AgentChunkEventOneOf8 {
    /**
     * 
     * @type {string}
     * @memberof AgentChunkEventOneOf8
     */
    command?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AgentChunkEventOneOf8
     */
    isFinished?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof AgentChunkEventOneOf8
     */
    result: string;
    /**
     * 
     * @type {AgentChunkEventOneOf8TypeEnum}
     * @memberof AgentChunkEventOneOf8
     */
    type: AgentChunkEventOneOf8TypeEnum;
}


/**
 * @export
 */
export const AgentChunkEventOneOf8TypeEnum = {
    AttemptCompletion: 'attempt_completion'
} as const;
export type AgentChunkEventOneOf8TypeEnum = typeof AgentChunkEventOneOf8TypeEnum[keyof typeof AgentChunkEventOneOf8TypeEnum];


/**
 * Check if a given object implements the AgentChunkEventOneOf8 interface.
 */
export function instanceOfAgentChunkEventOneOf8(value: object): value is AgentChunkEventOneOf8 {
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AgentChunkEventOneOf8FromJSON(json: any): AgentChunkEventOneOf8 {
    return AgentChunkEventOneOf8FromJSONTyped(json, false);
}

export function AgentChunkEventOneOf8FromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentChunkEventOneOf8 {
    if (json == null) {
        return json;
    }
    return {
        
        'command': json['command'] == null ? undefined : json['command'],
        'isFinished': json['is_finished'] == null ? undefined : json['is_finished'],
        'result': json['result'],
        'type': json['type'],
    };
}

export function AgentChunkEventOneOf8ToJSON(json: any): AgentChunkEventOneOf8 {
    return AgentChunkEventOneOf8ToJSONTyped(json, false);
}

export function AgentChunkEventOneOf8ToJSONTyped(value?: AgentChunkEventOneOf8 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command': value['command'],
        'is_finished': value['isFinished'],
        'result': value['result'],
        'type': value['type'],
    };
}

