/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for getting agent status
 * @export
 * @interface AgentStatusResponse
 */
export interface AgentStatusResponse {
    /**
     * TODO: add English documentation
     * @type {boolean}
     * @memberof AgentStatusResponse
     */
    isRunning: boolean;
    /**
     * TODO: add English documentation
     * @type {number}
     * @memberof AgentStatusResponse
     */
    progress: number;
    /**
     * TODO: add English documentation
     * @type {string}
     * @memberof AgentStatusResponse
     */
    state: string;
}

/**
 * Check if a given object implements the AgentStatusResponse interface.
 */
export function instanceOfAgentStatusResponse(value: object): value is AgentStatusResponse {
    if (!('isRunning' in value) || value['isRunning'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function AgentStatusResponseFromJSON(json: any): AgentStatusResponse {
    return AgentStatusResponseFromJSONTyped(json, false);
}

export function AgentStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isRunning': json['is_running'],
        'progress': json['progress'],
        'state': json['state'],
    };
}

export function AgentStatusResponseToJSON(json: any): AgentStatusResponse {
    return AgentStatusResponseToJSONTyped(json, false);
}

export function AgentStatusResponseToJSONTyped(value?: AgentStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_running': value['isRunning'],
        'progress': value['progress'],
        'state': value['state'],
    };
}

