/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Allowed tenant metadata. Denied tenants and policy internals are omitted.
 * @export
 * @interface AllowedTenantResponse
 */
export interface AllowedTenantResponse {
    /**
     * 
     * @type {string}
     * @memberof AllowedTenantResponse
     */
    alias: string;
    /**
     * 
     * @type {string}
     * @memberof AllowedTenantResponse
     */
    executionMode: string;
    /**
     * 
     * @type {string}
     * @memberof AllowedTenantResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AllowedTenantResponse
     */
    parentTenantId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AllowedTenantResponse
     */
    rootTenantId: string;
    /**
     * 
     * @type {string}
     * @memberof AllowedTenantResponse
     */
    tenantId: string;
}

/**
 * Check if a given object implements the AllowedTenantResponse interface.
 */
export function instanceOfAllowedTenantResponse(value: object): value is AllowedTenantResponse {
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('executionMode' in value) || value['executionMode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('rootTenantId' in value) || value['rootTenantId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function AllowedTenantResponseFromJSON(json: any): AllowedTenantResponse {
    return AllowedTenantResponseFromJSONTyped(json, false);
}

export function AllowedTenantResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllowedTenantResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'executionMode': json['executionMode'],
        'name': json['name'],
        'parentTenantId': json['parentTenantId'] == null ? undefined : json['parentTenantId'],
        'rootTenantId': json['rootTenantId'],
        'tenantId': json['tenantId'],
    };
}

export function AllowedTenantResponseToJSON(json: any): AllowedTenantResponse {
    return AllowedTenantResponseToJSONTyped(json, false);
}

export function AllowedTenantResponseToJSONTyped(value?: AllowedTenantResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'executionMode': value['executionMode'],
        'name': value['name'],
        'parentTenantId': value['parentTenantId'],
        'rootTenantId': value['rootTenantId'],
        'tenantId': value['tenantId'],
    };
}

