/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatRoom
 */
export interface ChatRoom {
    /**
     * 
     * @type {Date}
     * @memberof ChatRoom
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ChatRoom
     */
    id: string;
    /**
     * Arbitrary JSON metadata for the chatroom.
     * Common fields include:
     * - `user_id`: External user identifier (e.g., LINE user ID) for filtering
     * - `comparison_group_id`: ID to group chatrooms for model comparison
     * - `comparison_group_name`: Human-readable name for the comparison group
     * @type {any}
     * @memberof ChatRoom
     */
    metadata: any | null;
    /**
     * 
     * @type {string}
     * @memberof ChatRoom
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ChatRoom
     */
    operatorId: string;
    /**
     * 
     * @type {string}
     * @memberof ChatRoom
     */
    ownerId: string;
    /**
     * 
     * @type {Date}
     * @memberof ChatRoom
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ChatRoom interface.
 */
export function instanceOfChatRoom(value: object): value is ChatRoom {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('operatorId' in value) || value['operatorId'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ChatRoomFromJSON(json: any): ChatRoom {
    return ChatRoomFromJSONTyped(json, false);
}

export function ChatRoomFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatRoom {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'metadata': json['metadata'],
        'name': json['name'],
        'operatorId': json['operator_id'],
        'ownerId': json['owner_id'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ChatRoomToJSON(json: any): ChatRoom {
    return ChatRoomToJSONTyped(json, false);
}

export function ChatRoomToJSONTyped(value?: ChatRoom | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'metadata': value['metadata'],
        'name': value['name'],
        'operator_id': value['operatorId'],
        'owner_id': value['ownerId'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

