/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Controls chatroom name auto-generation behavior.
 * @export
 */
export const ChatroomNameGeneration = {
    Always: 'always',
    Never: 'never',
    FirstOnly: 'first_only'
} as const;
export type ChatroomNameGeneration = typeof ChatroomNameGeneration[keyof typeof ChatroomNameGeneration];


export function instanceOfChatroomNameGeneration(value: any): boolean {
    for (const key in ChatroomNameGeneration) {
        if (Object.prototype.hasOwnProperty.call(ChatroomNameGeneration, key)) {
            if (ChatroomNameGeneration[key as keyof typeof ChatroomNameGeneration] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ChatroomNameGenerationFromJSON(json: any): ChatroomNameGeneration {
    return ChatroomNameGenerationFromJSONTyped(json, false);
}

export function ChatroomNameGenerationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatroomNameGeneration {
    return json as ChatroomNameGeneration;
}

export function ChatroomNameGenerationToJSON(value?: ChatroomNameGeneration | null): any {
    return value as any;
}

export function ChatroomNameGenerationToJSONTyped(value: any, ignoreDiscriminator: boolean): ChatroomNameGeneration {
    return value as ChatroomNameGeneration;
}

