/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ChatRole = {
    System: 'system',
    User: 'user',
    Assistant: 'assistant'
} as const;
export type ChatRole = typeof ChatRole[keyof typeof ChatRole];


export function instanceOfChatRole(value: any): boolean {
    for (const key in ChatRole) {
        if (Object.prototype.hasOwnProperty.call(ChatRole, key)) {
            if (ChatRole[key as keyof typeof ChatRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ChatRoleFromJSON(json: any): ChatRole {
    return ChatRoleFromJSONTyped(json, false);
}

export function ChatRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatRole {
    return json as ChatRole;
}

export function ChatRoleToJSON(value?: ChatRole | null): any {
    return value as any;
}

export function ChatRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): ChatRole {
    return value as ChatRole;
}

