/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Content part type for array messages
 * @export
 * @interface ContentPart
 */
export interface ContentPart {
    /**
     * The text content if type is "text"
     * @type {string}
     * @memberof ContentPart
     */
    text?: string | null;
    /**
     * The type of the content part
     * @type {string}
     * @memberof ContentPart
     */
    type: string;
}

/**
 * Check if a given object implements the ContentPart interface.
 */
export function instanceOfContentPart(value: object): value is ContentPart {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ContentPartFromJSON(json: any): ContentPart {
    return ContentPartFromJSONTyped(json, false);
}

export function ContentPartFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentPart {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'type': json['type'],
    };
}

export function ContentPartToJSON(json: any): ContentPart {
    return ContentPartToJSONTyped(json, false);
}

export function ContentPartToJSONTyped(value?: ContentPart | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'type': value['type'],
    };
}

