/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to create a service account
 * @export
 * @interface CreateServiceAccountRequest
 */
export interface CreateServiceAccountRequest {
    /**
     * Display name
     * @type {string}
     * @memberof CreateServiceAccountRequest
     */
    name: string;
    /**
     * Tenant ID the service account belongs to
     * @type {string}
     * @memberof CreateServiceAccountRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the CreateServiceAccountRequest interface.
 */
export function instanceOfCreateServiceAccountRequest(value: object): value is CreateServiceAccountRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function CreateServiceAccountRequestFromJSON(json: any): CreateServiceAccountRequest {
    return CreateServiceAccountRequestFromJSONTyped(json, false);
}

export function CreateServiceAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateServiceAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'tenantId': json['tenantId'],
    };
}

export function CreateServiceAccountRequestToJSON(json: any): CreateServiceAccountRequest {
    return CreateServiceAccountRequestToJSONTyped(json, false);
}

export function CreateServiceAccountRequestToJSONTyped(value?: CreateServiceAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'tenantId': value['tenantId'],
    };
}

