/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to create an API key
 * @export
 * @interface CreateApiKeyRequest
 */
export interface CreateApiKeyRequest {
    /**
     * Display name for the API key
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    name: string;
    /**
     * Operator ID
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    operatorId: string;
}

/**
 * Check if a given object implements the CreateApiKeyRequest interface.
 */
export function instanceOfCreateApiKeyRequest(value: object): value is CreateApiKeyRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('operatorId' in value) || value['operatorId'] === undefined) return false;
    return true;
}

export function CreateApiKeyRequestFromJSON(json: any): CreateApiKeyRequest {
    return CreateApiKeyRequestFromJSONTyped(json, false);
}

export function CreateApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'operatorId': json['operatorId'],
    };
}

export function CreateApiKeyRequestToJSON(json: any): CreateApiKeyRequest {
    return CreateApiKeyRequestToJSONTyped(json, false);
}

export function CreateApiKeyRequestToJSONTyped(value?: CreateApiKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'operatorId': value['operatorId'],
    };
}

