/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for delete operation
 * @export
 * @interface DeleteServiceAccountResponse
 */
export interface DeleteServiceAccountResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteServiceAccountResponse
     */
    id: string;
}

/**
 * Check if a given object implements the DeleteServiceAccountResponse interface.
 */
export function instanceOfDeleteServiceAccountResponse(value: object): value is DeleteServiceAccountResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DeleteServiceAccountResponseFromJSON(json: any): DeleteServiceAccountResponse {
    return DeleteServiceAccountResponseFromJSONTyped(json, false);
}

export function DeleteServiceAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteServiceAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DeleteServiceAccountResponseToJSON(json: any): DeleteServiceAccountResponse {
    return DeleteServiceAccountResponseToJSONTyped(json, false);
}

export function DeleteServiceAccountResponseToJSONTyped(value?: DeleteServiceAccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

