/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentSessionEntry } from './AgentSessionEntry';
import {
    AgentSessionEntryFromJSON,
    AgentSessionEntryFromJSONTyped,
    AgentSessionEntryToJSON,
    AgentSessionEntryToJSONTyped,
} from './AgentSessionEntry';

/**
 * Output containing the list of sessions.
 * @export
 * @interface ListAgentSessionsOutputData
 */
export interface ListAgentSessionsOutputData {
    /**
     * 
     * @type {Array<AgentSessionEntry>}
     * @memberof ListAgentSessionsOutputData
     */
    sessions: Array<AgentSessionEntry>;
}

/**
 * Check if a given object implements the ListAgentSessionsOutputData interface.
 */
export function instanceOfListAgentSessionsOutputData(value: object): value is ListAgentSessionsOutputData {
    if (!('sessions' in value) || value['sessions'] === undefined) return false;
    return true;
}

export function ListAgentSessionsOutputDataFromJSON(json: any): ListAgentSessionsOutputData {
    return ListAgentSessionsOutputDataFromJSONTyped(json, false);
}

export function ListAgentSessionsOutputDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAgentSessionsOutputData {
    if (json == null) {
        return json;
    }
    return {
        
        'sessions': ((json['sessions'] as Array<any>).map(AgentSessionEntryFromJSON)),
    };
}

export function ListAgentSessionsOutputDataToJSON(json: any): ListAgentSessionsOutputData {
    return ListAgentSessionsOutputDataToJSONTyped(json, false);
}

export function ListAgentSessionsOutputDataToJSONTyped(value?: ListAgentSessionsOutputData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessions': ((value['sessions'] as Array<any>).map(AgentSessionEntryToJSON)),
    };
}

