/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectionResponse } from './ConnectionResponse';
import {
    ConnectionResponseFromJSON,
    ConnectionResponseFromJSONTyped,
    ConnectionResponseToJSON,
    ConnectionResponseToJSONTyped,
} from './ConnectionResponse';

/**
 * 
 * @export
 * @interface ListConnectionsResponse
 */
export interface ListConnectionsResponse {
    /**
     * 
     * @type {Array<ConnectionResponse>}
     * @memberof ListConnectionsResponse
     */
    connections: Array<ConnectionResponse>;
}

/**
 * Check if a given object implements the ListConnectionsResponse interface.
 */
export function instanceOfListConnectionsResponse(value: object): value is ListConnectionsResponse {
    if (!('connections' in value) || value['connections'] === undefined) return false;
    return true;
}

export function ListConnectionsResponseFromJSON(json: any): ListConnectionsResponse {
    return ListConnectionsResponseFromJSONTyped(json, false);
}

export function ListConnectionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConnectionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'connections': ((json['connections'] as Array<any>).map(ConnectionResponseFromJSON)),
    };
}

export function ListConnectionsResponseToJSON(json: any): ListConnectionsResponse {
    return ListConnectionsResponseToJSONTyped(json, false);
}

export function ListConnectionsResponseToJSONTyped(value?: ListConnectionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connections': ((value['connections'] as Array<any>).map(ConnectionResponseToJSON)),
    };
}

