/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Memory settings for context building
 * @export
 * @interface MemorySettingsRequest
 */
export interface MemorySettingsRequest {
    /**
     * Whether to extract memory from the message
     * @type {boolean}
     * @memberof MemorySettingsRequest
     */
    extractMemory: boolean;
    /**
     * Maximum number of memories to retrieve
     * @type {number}
     * @memberof MemorySettingsRequest
     */
    maxMemories: number;
    /**
     * Minimum relevance score for memory retrieval (0.0 to 1.0)
     * @type {number}
     * @memberof MemorySettingsRequest
     */
    minRelevanceScore: number;
}

/**
 * Check if a given object implements the MemorySettingsRequest interface.
 */
export function instanceOfMemorySettingsRequest(value: object): value is MemorySettingsRequest {
    if (!('extractMemory' in value) || value['extractMemory'] === undefined) return false;
    if (!('maxMemories' in value) || value['maxMemories'] === undefined) return false;
    if (!('minRelevanceScore' in value) || value['minRelevanceScore'] === undefined) return false;
    return true;
}

export function MemorySettingsRequestFromJSON(json: any): MemorySettingsRequest {
    return MemorySettingsRequestFromJSONTyped(json, false);
}

export function MemorySettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemorySettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'extractMemory': json['extract_memory'],
        'maxMemories': json['max_memories'],
        'minRelevanceScore': json['min_relevance_score'],
    };
}

export function MemorySettingsRequestToJSON(json: any): MemorySettingsRequest {
    return MemorySettingsRequestToJSONTyped(json, false);
}

export function MemorySettingsRequestToJSONTyped(value?: MemorySettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extract_memory': value['extractMemory'],
        'max_memories': value['maxMemories'],
        'min_relevance_score': value['minRelevanceScore'],
    };
}

