/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageContent } from './MessageContent';
import {
    MessageContentFromJSON,
    MessageContentFromJSONTyped,
    MessageContentToJSON,
    MessageContentToJSONTyped,
} from './MessageContent';
import type { ToolCallResponse } from './ToolCallResponse';
import {
    ToolCallResponseFromJSON,
    ToolCallResponseFromJSONTyped,
    ToolCallResponseToJSON,
    ToolCallResponseToJSONTyped,
} from './ToolCallResponse';

/**
 * Message type for request/response handling
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * The content of the message
     * @type {MessageContent}
     * @memberof Message
     */
    content?: MessageContent | null;
    /**
     * The role of the message author
     * @type {string}
     * @memberof Message
     */
    role: string;
    /**
     * The tool calls made by the assistant
     * @type {Array<ToolCallResponse>}
     * @memberof Message
     */
    toolCalls?: Array<ToolCallResponse> | null;
}

/**
 * Check if a given object implements the Message interface.
 */
export function instanceOfMessage(value: object): value is Message {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function MessageFromJSON(json: any): Message {
    return MessageFromJSONTyped(json, false);
}

export function MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Message {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : MessageContentFromJSON(json['content']),
        'role': json['role'],
        'toolCalls': json['tool_calls'] == null ? undefined : ((json['tool_calls'] as Array<any>).map(ToolCallResponseFromJSON)),
    };
}

export function MessageToJSON(json: any): Message {
    return MessageToJSONTyped(json, false);
}

export function MessageToJSONTyped(value?: Message | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': MessageContentToJSON(value['content']),
        'role': value['role'],
        'tool_calls': value['toolCalls'] == null ? undefined : ((value['toolCalls'] as Array<any>).map(ToolCallResponseToJSON)),
    };
}

