/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SupportedFeature } from './SupportedFeature';
import {
    SupportedFeatureFromJSON,
    SupportedFeatureFromJSONTyped,
    SupportedFeatureToJSON,
    SupportedFeatureToJSONTyped,
} from './SupportedFeature';

/**
 * 
 * @export
 * @interface ModelInfo
 */
export interface ModelInfo {
    /**
     * Maximum context window size in tokens.
     * @type {number}
     * @memberof ModelInfo
     */
    contextWindow?: number | null;
    /**
     * Human-readable description of the model.
     * @type {string}
     * @memberof ModelInfo
     */
    description?: string | null;
    /**
     * Unique model identifier in `provider/model-name` format.
     * @type {string}
     * @memberof ModelInfo
     */
    id: string;
    /**
     * Maximum number of output tokens.
     * @type {number}
     * @memberof ModelInfo
     */
    maxOutputTokens?: number | null;
    /**
     * Model name.
     * @type {string}
     * @memberof ModelInfo
     */
    name: string;
    /**
     * Provider name (e.g. anthropic, openai, google_ai).
     * @type {string}
     * @memberof ModelInfo
     */
    provider: string;
    /**
     * List of features supported by this model.
     * @type {Array<SupportedFeature>}
     * @memberof ModelInfo
     */
    supportedFeatures: Array<SupportedFeature>;
}

/**
 * Check if a given object implements the ModelInfo interface.
 */
export function instanceOfModelInfo(value: object): value is ModelInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('supportedFeatures' in value) || value['supportedFeatures'] === undefined) return false;
    return true;
}

export function ModelInfoFromJSON(json: any): ModelInfo {
    return ModelInfoFromJSONTyped(json, false);
}

export function ModelInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'contextWindow': json['context_window'] == null ? undefined : json['context_window'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'maxOutputTokens': json['max_output_tokens'] == null ? undefined : json['max_output_tokens'],
        'name': json['name'],
        'provider': json['provider'],
        'supportedFeatures': ((json['supported_features'] as Array<any>).map(SupportedFeatureFromJSON)),
    };
}

export function ModelInfoToJSON(json: any): ModelInfo {
    return ModelInfoToJSONTyped(json, false);
}

export function ModelInfoToJSONTyped(value?: ModelInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context_window': value['contextWindow'],
        'description': value['description'],
        'id': value['id'],
        'max_output_tokens': value['maxOutputTokens'],
        'name': value['name'],
        'provider': value['provider'],
        'supported_features': ((value['supportedFeatures'] as Array<any>).map(SupportedFeatureToJSON)),
    };
}

