/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthCallbackResponse
 */
export interface OAuthCallbackResponse {
    /**
     * 
     * @type {string}
     * @memberof OAuthCallbackResponse
     */
    operatorId: string;
}

/**
 * Check if a given object implements the OAuthCallbackResponse interface.
 */
export function instanceOfOAuthCallbackResponse(value: object): value is OAuthCallbackResponse {
    if (!('operatorId' in value) || value['operatorId'] === undefined) return false;
    return true;
}

export function OAuthCallbackResponseFromJSON(json: any): OAuthCallbackResponse {
    return OAuthCallbackResponseFromJSONTyped(json, false);
}

export function OAuthCallbackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthCallbackResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'operatorId': json['operatorId'],
    };
}

export function OAuthCallbackResponseToJSON(json: any): OAuthCallbackResponse {
    return OAuthCallbackResponseToJSONTyped(json, false);
}

export function OAuthCallbackResponseToJSONTyped(value?: OAuthCallbackResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operatorId': value['operatorId'],
    };
}

