/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OAuthTokenResponse } from './OAuthTokenResponse';
import {
    OAuthTokenResponseFromJSON,
    OAuthTokenResponseFromJSONTyped,
    OAuthTokenResponseToJSON,
    OAuthTokenResponseToJSONTyped,
} from './OAuthTokenResponse';

/**
 * Response for OAuth token list
 * @export
 * @interface OAuthTokenListResponse
 */
export interface OAuthTokenListResponse {
    /**
     * 
     * @type {Array<OAuthTokenResponse>}
     * @memberof OAuthTokenListResponse
     */
    tokens: Array<OAuthTokenResponse>;
}

/**
 * Check if a given object implements the OAuthTokenListResponse interface.
 */
export function instanceOfOAuthTokenListResponse(value: object): value is OAuthTokenListResponse {
    if (!('tokens' in value) || value['tokens'] === undefined) return false;
    return true;
}

export function OAuthTokenListResponseFromJSON(json: any): OAuthTokenListResponse {
    return OAuthTokenListResponseFromJSONTyped(json, false);
}

export function OAuthTokenListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthTokenListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tokens': ((json['tokens'] as Array<any>).map(OAuthTokenResponseFromJSON)),
    };
}

export function OAuthTokenListResponseToJSON(json: any): OAuthTokenListResponse {
    return OAuthTokenListResponseToJSONTyped(json, false);
}

export function OAuthTokenListResponseToJSONTyped(value?: OAuthTokenListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokens': ((value['tokens'] as Array<any>).map(OAuthTokenResponseToJSON)),
    };
}

