/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for newly created OAuth2 client (includes plain-text secret)
 * @export
 * @interface OAuth2CreateClientResponse
 */
export interface OAuth2CreateClientResponse {
    /**
     * Allowed scopes
     * @type {Array<string>}
     * @memberof OAuth2CreateClientResponse
     */
    allowedScopes: Array<string>;
    /**
     * Authentication mode
     * @type {string}
     * @memberof OAuth2CreateClientResponse
     */
    authMode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OAuth2CreateClientResponse
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof OAuth2CreateClientResponse
     */
    clientSecret: string;
    /**
     * 
     * @type {string}
     * @memberof OAuth2CreateClientResponse
     */
    createdAt: string;
    /**
     * Allowed grant types
     * @type {Array<string>}
     * @memberof OAuth2CreateClientResponse
     */
    grantTypes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OAuth2CreateClientResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OAuth2CreateClientResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OAuth2CreateClientResponse
     */
    providerUserPoolId?: string | null;
    /**
     * Allowed redirect URIs
     * @type {Array<string>}
     * @memberof OAuth2CreateClientResponse
     */
    redirectUris: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OAuth2CreateClientResponse
     */
    status: string;
    /**
     * 
     * @type {boolean}
     * @memberof OAuth2CreateClientResponse
     */
    useTachyonUserPool: boolean;
    /**
     * 
     * @type {string}
     * @memberof OAuth2CreateClientResponse
     */
    userPoolId?: string | null;
}

/**
 * Check if a given object implements the OAuth2CreateClientResponse interface.
 */
export function instanceOfOAuth2CreateClientResponse(value: object): value is OAuth2CreateClientResponse {
    if (!('allowedScopes' in value) || value['allowedScopes'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('clientSecret' in value) || value['clientSecret'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('grantTypes' in value) || value['grantTypes'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('redirectUris' in value) || value['redirectUris'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('useTachyonUserPool' in value) || value['useTachyonUserPool'] === undefined) return false;
    return true;
}

export function OAuth2CreateClientResponseFromJSON(json: any): OAuth2CreateClientResponse {
    return OAuth2CreateClientResponseFromJSONTyped(json, false);
}

export function OAuth2CreateClientResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuth2CreateClientResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedScopes': json['allowedScopes'],
        'authMode': json['authMode'] == null ? undefined : json['authMode'],
        'clientId': json['clientId'],
        'clientSecret': json['clientSecret'],
        'createdAt': json['createdAt'],
        'grantTypes': json['grantTypes'],
        'id': json['id'],
        'name': json['name'],
        'providerUserPoolId': json['providerUserPoolId'] == null ? undefined : json['providerUserPoolId'],
        'redirectUris': json['redirectUris'],
        'status': json['status'],
        'useTachyonUserPool': json['useTachyonUserPool'],
        'userPoolId': json['userPoolId'] == null ? undefined : json['userPoolId'],
    };
}

export function OAuth2CreateClientResponseToJSON(json: any): OAuth2CreateClientResponse {
    return OAuth2CreateClientResponseToJSONTyped(json, false);
}

export function OAuth2CreateClientResponseToJSONTyped(value?: OAuth2CreateClientResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowedScopes': value['allowedScopes'],
        'authMode': value['authMode'],
        'clientId': value['clientId'],
        'clientSecret': value['clientSecret'],
        'createdAt': value['createdAt'],
        'grantTypes': value['grantTypes'],
        'id': value['id'],
        'name': value['name'],
        'providerUserPoolId': value['providerUserPoolId'],
        'redirectUris': value['redirectUris'],
        'status': value['status'],
        'useTachyonUserPool': value['useTachyonUserPool'],
        'userPoolId': value['userPoolId'],
    };
}

