/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ObjectMappingItemResponse } from './ObjectMappingItemResponse';
import {
    ObjectMappingItemResponseFromJSON,
    ObjectMappingItemResponseFromJSONTyped,
    ObjectMappingItemResponseToJSON,
    ObjectMappingItemResponseToJSONTyped,
} from './ObjectMappingItemResponse';

/**
 * Response for object mapping list
 * @export
 * @interface ObjectMappingListResponse
 */
export interface ObjectMappingListResponse {
    /**
     * 
     * @type {Array<ObjectMappingItemResponse>}
     * @memberof ObjectMappingListResponse
     */
    items: Array<ObjectMappingItemResponse>;
}

/**
 * Check if a given object implements the ObjectMappingListResponse interface.
 */
export function instanceOfObjectMappingListResponse(value: object): value is ObjectMappingListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ObjectMappingListResponseFromJSON(json: any): ObjectMappingListResponse {
    return ObjectMappingListResponseFromJSONTyped(json, false);
}

export function ObjectMappingListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectMappingListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ObjectMappingItemResponseFromJSON)),
    };
}

export function ObjectMappingListResponseToJSON(json: any): ObjectMappingListResponse {
    return ObjectMappingListResponseToJSONTyped(json, false);
}

export function ObjectMappingListResponseToJSONTyped(value?: ObjectMappingListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ObjectMappingItemResponseToJSON)),
    };
}

