/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantMappingResponse } from './TenantMappingResponse';
import {
    TenantMappingResponseFromJSON,
    TenantMappingResponseFromJSONTyped,
    TenantMappingResponseToJSON,
    TenantMappingResponseToJSONTyped,
} from './TenantMappingResponse';
import type { ObjectMappingResponse } from './ObjectMappingResponse';
import {
    ObjectMappingResponseFromJSON,
    ObjectMappingResponseFromJSONTyped,
    ObjectMappingResponseToJSON,
    ObjectMappingResponseToJSONTyped,
} from './ObjectMappingResponse';

/**
 * Single item in object mapping list
 * @export
 * @interface ObjectMappingItemResponse
 */
export interface ObjectMappingItemResponse {
    /**
     * 
     * @type {ObjectMappingResponse}
     * @memberof ObjectMappingItemResponse
     */
    objectMapping: ObjectMappingResponse;
    /**
     * 
     * @type {TenantMappingResponse}
     * @memberof ObjectMappingItemResponse
     */
    tenantMapping?: TenantMappingResponse | null;
}

/**
 * Check if a given object implements the ObjectMappingItemResponse interface.
 */
export function instanceOfObjectMappingItemResponse(value: object): value is ObjectMappingItemResponse {
    if (!('objectMapping' in value) || value['objectMapping'] === undefined) return false;
    return true;
}

export function ObjectMappingItemResponseFromJSON(json: any): ObjectMappingItemResponse {
    return ObjectMappingItemResponseFromJSONTyped(json, false);
}

export function ObjectMappingItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectMappingItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'objectMapping': ObjectMappingResponseFromJSON(json['objectMapping']),
        'tenantMapping': json['tenantMapping'] == null ? undefined : TenantMappingResponseFromJSON(json['tenantMapping']),
    };
}

export function ObjectMappingItemResponseToJSON(json: any): ObjectMappingItemResponse {
    return ObjectMappingItemResponseToJSONTyped(json, false);
}

export function ObjectMappingItemResponseToJSONTyped(value?: ObjectMappingItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objectMapping': ObjectMappingResponseToJSON(value['objectMapping']),
        'tenantMapping': TenantMappingResponseToJSON(value['tenantMapping']),
    };
}

