/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OffsetPaginator
 */
export interface OffsetPaginator {
    /**
     * 
     * @type {number}
     * @memberof OffsetPaginator
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof OffsetPaginator
     */
    itemsPerPage: number;
    /**
     * 
     * @type {number}
     * @memberof OffsetPaginator
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof OffsetPaginator
     */
    totalPages: number;
}

/**
 * Check if a given object implements the OffsetPaginator interface.
 */
export function instanceOfOffsetPaginator(value: object): value is OffsetPaginator {
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('itemsPerPage' in value) || value['itemsPerPage'] === undefined) return false;
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function OffsetPaginatorFromJSON(json: any): OffsetPaginator {
    return OffsetPaginatorFromJSONTyped(json, false);
}

export function OffsetPaginatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): OffsetPaginator {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'],
        'itemsPerPage': json['items_per_page'],
        'totalItems': json['total_items'],
        'totalPages': json['total_pages'],
    };
}

export function OffsetPaginatorToJSON(json: any): OffsetPaginator {
    return OffsetPaginatorToJSONTyped(json, false);
}

export function OffsetPaginatorToJSONTyped(value?: OffsetPaginator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'items_per_page': value['itemsPerPage'],
        'total_items': value['totalItems'],
        'total_pages': value['totalPages'],
    };
}

