/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response DTO for an operator
 * @export
 * @interface OperatorResponse
 */
export interface OperatorResponse {
    /**
     * 
     * @type {string}
     * @memberof OperatorResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OperatorResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OperatorResponse
     */
    operatorName: string;
    /**
     * 
     * @type {string}
     * @memberof OperatorResponse
     */
    platformId: string;
}

/**
 * Check if a given object implements the OperatorResponse interface.
 */
export function instanceOfOperatorResponse(value: object): value is OperatorResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('operatorName' in value) || value['operatorName'] === undefined) return false;
    if (!('platformId' in value) || value['platformId'] === undefined) return false;
    return true;
}

export function OperatorResponseFromJSON(json: any): OperatorResponse {
    return OperatorResponseFromJSONTyped(json, false);
}

export function OperatorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'operatorName': json['operatorName'],
        'platformId': json['platformId'],
    };
}

export function OperatorResponseToJSON(json: any): OperatorResponse {
    return OperatorResponseToJSONTyped(json, false);
}

export function OperatorResponseToJSONTyped(value?: OperatorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'operatorName': value['operatorName'],
        'platformId': value['platformId'],
    };
}

