/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartOneOf1
 */
export interface PartOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof PartOneOf1
     */
    image: string;
    /**
     * 
     * @type {PartOneOf1TypeEnum}
     * @memberof PartOneOf1
     */
    type: PartOneOf1TypeEnum;
}


/**
 * @export
 */
export const PartOneOf1TypeEnum = {
    Image: 'image'
} as const;
export type PartOneOf1TypeEnum = typeof PartOneOf1TypeEnum[keyof typeof PartOneOf1TypeEnum];


/**
 * Check if a given object implements the PartOneOf1 interface.
 */
export function instanceOfPartOneOf1(value: object): value is PartOneOf1 {
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PartOneOf1FromJSON(json: any): PartOneOf1 {
    return PartOneOf1FromJSONTyped(json, false);
}

export function PartOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PartOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
        'type': json['type'],
    };
}

export function PartOneOf1ToJSON(json: any): PartOneOf1 {
    return PartOneOf1ToJSONTyped(json, false);
}

export function PartOneOf1ToJSONTyped(value?: PartOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
        'type': value['type'],
    };
}

