/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Product variant response
 * @export
 * @interface ProductVariantResponse
 */
export interface ProductVariantResponse {
    /**
     * Variant code
     * @type {string}
     * @memberof ProductVariantResponse
     */
    code: string;
    /**
     * Created at
     * @type {Date}
     * @memberof ProductVariantResponse
     */
    createdAt: Date;
    /**
     * Variant ID
     * @type {string}
     * @memberof ProductVariantResponse
     */
    id: string;
    /**
     * 
     * @type {any}
     * @memberof ProductVariantResponse
     */
    metadata: any | null;
    /**
     * Variant name
     * @type {string}
     * @memberof ProductVariantResponse
     */
    name: string;
    /**
     * Product ID
     * @type {string}
     * @memberof ProductVariantResponse
     */
    productId: string;
    /**
     * Variant status
     * @type {string}
     * @memberof ProductVariantResponse
     */
    status: string;
    /**
     * Tenant ID
     * @type {string}
     * @memberof ProductVariantResponse
     */
    tenantId: string;
    /**
     * Updated at
     * @type {Date}
     * @memberof ProductVariantResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ProductVariantResponse interface.
 */
export function instanceOfProductVariantResponse(value: object): value is ProductVariantResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProductVariantResponseFromJSON(json: any): ProductVariantResponse {
    return ProductVariantResponseFromJSONTyped(json, false);
}

export function ProductVariantResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVariantResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'createdAt': (new Date(json['createdAt'])),
        'id': json['id'],
        'metadata': json['metadata'],
        'name': json['name'],
        'productId': json['productId'],
        'status': json['status'],
        'tenantId': json['tenantId'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ProductVariantResponseToJSON(json: any): ProductVariantResponse {
    return ProductVariantResponseToJSONTyped(json, false);
}

export function ProductVariantResponseToJSONTyped(value?: ProductVariantResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'createdAt': value['createdAt'].toISOString(),
        'id': value['id'],
        'metadata': value['metadata'],
        'name': value['name'],
        'productId': value['productId'],
        'status': value['status'],
        'tenantId': value['tenantId'],
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

