/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuoteResponse } from './QuoteResponse';
import {
    QuoteResponseFromJSON,
    QuoteResponseFromJSONTyped,
    QuoteResponseToJSON,
    QuoteResponseToJSONTyped,
} from './QuoteResponse';

/**
 * Quote list response
 * @export
 * @interface QuoteListResponse
 */
export interface QuoteListResponse {
    /**
     * Quote items
     * @type {Array<QuoteResponse>}
     * @memberof QuoteListResponse
     */
    items: Array<QuoteResponse>;
}

/**
 * Check if a given object implements the QuoteListResponse interface.
 */
export function instanceOfQuoteListResponse(value: object): value is QuoteListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function QuoteListResponseFromJSON(json: any): QuoteListResponse {
    return QuoteListResponseFromJSONTyped(json, false);
}

export function QuoteListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuoteListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(QuoteResponseFromJSON)),
    };
}

export function QuoteListResponseToJSON(json: any): QuoteListResponse {
    return QuoteListResponseToJSONTyped(json, false);
}

export function QuoteListResponseToJSONTyped(value?: QuoteListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(QuoteResponseToJSON)),
    };
}

