/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceAccountResponse } from './ServiceAccountResponse';
import {
    ServiceAccountResponseFromJSON,
    ServiceAccountResponseFromJSONTyped,
    ServiceAccountResponseToJSON,
    ServiceAccountResponseToJSONTyped,
} from './ServiceAccountResponse';

/**
 * Response for service account list
 * @export
 * @interface ServiceAccountListResponse
 */
export interface ServiceAccountListResponse {
    /**
     * 
     * @type {Array<ServiceAccountResponse>}
     * @memberof ServiceAccountListResponse
     */
    serviceAccounts: Array<ServiceAccountResponse>;
}

/**
 * Check if a given object implements the ServiceAccountListResponse interface.
 */
export function instanceOfServiceAccountListResponse(value: object): value is ServiceAccountListResponse {
    if (!('serviceAccounts' in value) || value['serviceAccounts'] === undefined) return false;
    return true;
}

export function ServiceAccountListResponseFromJSON(json: any): ServiceAccountListResponse {
    return ServiceAccountListResponseFromJSONTyped(json, false);
}

export function ServiceAccountListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceAccountListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceAccounts': ((json['serviceAccounts'] as Array<any>).map(ServiceAccountResponseFromJSON)),
    };
}

export function ServiceAccountListResponseToJSON(json: any): ServiceAccountListResponse {
    return ServiceAccountListResponseToJSONTyped(json, false);
}

export function ServiceAccountListResponseToJSONTyped(value?: ServiceAccountListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceAccounts': ((value['serviceAccounts'] as Array<any>).map(ServiceAccountResponseToJSON)),
    };
}

