/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for a service account
 * @export
 * @interface ServiceAccountResponse
 */
export interface ServiceAccountResponse {
    /**
     * 
     * @type {string}
     * @memberof ServiceAccountResponse
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceAccountResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceAccountResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceAccountResponse
     */
    tenantId: string;
}

/**
 * Check if a given object implements the ServiceAccountResponse interface.
 */
export function instanceOfServiceAccountResponse(value: object): value is ServiceAccountResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function ServiceAccountResponseFromJSON(json: any): ServiceAccountResponse {
    return ServiceAccountResponseFromJSONTyped(json, false);
}

export function ServiceAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'id': json['id'],
        'name': json['name'],
        'tenantId': json['tenantId'],
    };
}

export function ServiceAccountResponseToJSON(json: any): ServiceAccountResponse {
    return ServiceAccountResponseToJSONTyped(json, false);
}

export function ServiceAccountResponseToJSONTyped(value?: ServiceAccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'id': value['id'],
        'name': value['name'],
        'tenantId': value['tenantId'],
    };
}

