/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for shipping availability check
 * @export
 * @interface ShippingAvailabilityResponse
 */
export interface ShippingAvailabilityResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ShippingAvailabilityResponse
     */
    available: boolean;
}

/**
 * Check if a given object implements the ShippingAvailabilityResponse interface.
 */
export function instanceOfShippingAvailabilityResponse(value: object): value is ShippingAvailabilityResponse {
    if (!('available' in value) || value['available'] === undefined) return false;
    return true;
}

export function ShippingAvailabilityResponseFromJSON(json: any): ShippingAvailabilityResponse {
    return ShippingAvailabilityResponseFromJSONTyped(json, false);
}

export function ShippingAvailabilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingAvailabilityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'available': json['available'],
    };
}

export function ShippingAvailabilityResponseToJSON(json: any): ShippingAvailabilityResponse {
    return ShippingAvailabilityResponseToJSONTyped(json, false);
}

export function ShippingAvailabilityResponseToJSONTyped(value?: ShippingAvailabilityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available': value['available'],
    };
}

