/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInWithPlatformRequest
 */
export interface SignInWithPlatformRequest {
    /**
     * 
     * @type {string}
     * @memberof SignInWithPlatformRequest
     */
    accessToken: string;
    /**
     * 
     * @type {boolean}
     * @memberof SignInWithPlatformRequest
     */
    allowSignUp?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof SignInWithPlatformRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignInWithPlatformRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignInWithPlatformRequest
     */
    platformId: string;
}

/**
 * Check if a given object implements the SignInWithPlatformRequest interface.
 */
export function instanceOfSignInWithPlatformRequest(value: object): value is SignInWithPlatformRequest {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('platformId' in value) || value['platformId'] === undefined) return false;
    return true;
}

export function SignInWithPlatformRequestFromJSON(json: any): SignInWithPlatformRequest {
    return SignInWithPlatformRequestFromJSONTyped(json, false);
}

export function SignInWithPlatformRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInWithPlatformRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'allowSignUp': json['allow_sign_up'] == null ? undefined : json['allow_sign_up'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'platformId': json['platform_id'],
    };
}

export function SignInWithPlatformRequestToJSON(json: any): SignInWithPlatformRequest {
    return SignInWithPlatformRequestToJSONTyped(json, false);
}

export function SignInWithPlatformRequestToJSONTyped(value?: SignInWithPlatformRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'allow_sign_up': value['allowSignUp'],
        'email': value['email'],
        'name': value['name'],
        'platform_id': value['platformId'],
    };
}

