/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Function } from './Function';
import {
    FunctionFromJSON,
    FunctionFromJSONTyped,
    FunctionToJSON,
    FunctionToJSONTyped,
} from './Function';

/**
 * Tool type for function calling
 * @export
 * @interface Tool
 */
export interface Tool {
    /**
     * The function definition
     * @type {Function}
     * @memberof Tool
     */
    _function: Function;
    /**
     * The type of the tool (currently only "function" is supported)
     * @type {string}
     * @memberof Tool
     */
    type: string;
}

/**
 * Check if a given object implements the Tool interface.
 */
export function instanceOfTool(value: object): value is Tool {
    if (!('_function' in value) || value['_function'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ToolFromJSON(json: any): Tool {
    return ToolFromJSONTyped(json, false);
}

export function ToolFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tool {
    if (json == null) {
        return json;
    }
    return {
        
        '_function': FunctionFromJSON(json['function']),
        'type': json['type'],
    };
}

export function ToolToJSON(json: any): Tool {
    return ToolToJSONTyped(json, false);
}

export function ToolToJSONTyped(value?: Tool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'function': FunctionToJSON(value['_function']),
        'type': value['type'],
    };
}

