/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Result submitted by the client for a pending tool call.
 * 
 * After receiving a `tool_call_pending` SSE event, the
 * client executes the tool and submits the result via
 * `POST /v1/llms/chatrooms/{chatroom_id}/agent/tool-result`.
 * 
 * # Example
 * 
 * ```json
 * {
 *   "tool_id": "ct_01JEXAMPLE",
 *   "result": "{\"rows\": [{\"id\": 1, \"name\": \"Alice\"}]}",
 *   "is_error": false
 * }
 * ```
 * @export
 * @interface ToolResultSubmission
 */
export interface ToolResultSubmission {
    /**
     * Set to `true` if the tool execution failed. The error
     * message in `result` is shown to the LLM so it can
     * attempt recovery or report the failure.
     * @type {boolean}
     * @memberof ToolResultSubmission
     */
    isError?: boolean;
    /**
     * The tool execution result as a string. For structured
     * data, serialize to JSON string. The content is passed
     * directly to the LLM as the tool's output.
     * @type {string}
     * @memberof ToolResultSubmission
     */
    result: string;
    /**
     * The `tool_id` from the `tool_call_pending` SSE event
     * that this result corresponds to.
     * @type {string}
     * @memberof ToolResultSubmission
     */
    toolId: string;
}

/**
 * Check if a given object implements the ToolResultSubmission interface.
 */
export function instanceOfToolResultSubmission(value: object): value is ToolResultSubmission {
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('toolId' in value) || value['toolId'] === undefined) return false;
    return true;
}

export function ToolResultSubmissionFromJSON(json: any): ToolResultSubmission {
    return ToolResultSubmissionFromJSONTyped(json, false);
}

export function ToolResultSubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolResultSubmission {
    if (json == null) {
        return json;
    }
    return {
        
        'isError': json['is_error'] == null ? undefined : json['is_error'],
        'result': json['result'],
        'toolId': json['tool_id'],
    };
}

export function ToolResultSubmissionToJSON(json: any): ToolResultSubmission {
    return ToolResultSubmissionToJSONTyped(json, false);
}

export function ToolResultSubmissionToJSONTyped(value?: ToolResultSubmission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_error': value['isError'],
        'result': value['result'],
        'tool_id': value['toolId'],
    };
}

