/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatRoom } from './ChatRoom';
import {
    ChatRoomFromJSON,
    ChatRoomFromJSONTyped,
    ChatRoomToJSON,
    ChatRoomToJSONTyped,
} from './ChatRoom';

/**
 * 
 * @export
 * @interface UpdateChatroomResponse
 */
export interface UpdateChatroomResponse {
    /**
     * Updated chatroom
     * @type {ChatRoom}
     * @memberof UpdateChatroomResponse
     */
    chatroom: ChatRoom;
}

/**
 * Check if a given object implements the UpdateChatroomResponse interface.
 */
export function instanceOfUpdateChatroomResponse(value: object): value is UpdateChatroomResponse {
    if (!('chatroom' in value) || value['chatroom'] === undefined) return false;
    return true;
}

export function UpdateChatroomResponseFromJSON(json: any): UpdateChatroomResponse {
    return UpdateChatroomResponseFromJSONTyped(json, false);
}

export function UpdateChatroomResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateChatroomResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chatroom': ChatRoomFromJSON(json['chatroom']),
    };
}

export function UpdateChatroomResponseToJSON(json: any): UpdateChatroomResponse {
    return UpdateChatroomResponseToJSONTyped(json, false);
}

export function UpdateChatroomResponseToJSONTyped(value?: UpdateChatroomResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chatroom': ChatRoomToJSON(value['chatroom']),
    };
}

