/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Update variation input
 * @export
 * @interface UpdateProductVariationRequest
 */
export interface UpdateProductVariationRequest {
    /**
     * Variation code
     * @type {string}
     * @memberof UpdateProductVariationRequest
     */
    code?: string | null;
    /**
     * Currency code
     * @type {string}
     * @memberof UpdateProductVariationRequest
     */
    currency?: string | null;
    /**
     * Variation ID
     * @type {string}
     * @memberof UpdateProductVariationRequest
     */
    id: string;
    /**
     * 
     * @type {any}
     * @memberof UpdateProductVariationRequest
     */
    metadata?: any | null;
    /**
     * Variation name
     * @type {string}
     * @memberof UpdateProductVariationRequest
     */
    name?: string | null;
    /**
     * Publication description
     * @type {string}
     * @memberof UpdateProductVariationRequest
     */
    publicationDescription?: string | null;
    /**
     * Publication name
     * @type {string}
     * @memberof UpdateProductVariationRequest
     */
    publicationName?: string | null;
    /**
     * Recurring billing frequency
     * @type {string}
     * @memberof UpdateProductVariationRequest
     */
    recurring?: string | null;
    /**
     * Variation status
     * @type {string}
     * @memberof UpdateProductVariationRequest
     */
    status?: string | null;
    /**
     * Unit amount
     * @type {number}
     * @memberof UpdateProductVariationRequest
     */
    unitAmount?: number | null;
}

/**
 * Check if a given object implements the UpdateProductVariationRequest interface.
 */
export function instanceOfUpdateProductVariationRequest(value: object): value is UpdateProductVariationRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UpdateProductVariationRequestFromJSON(json: any): UpdateProductVariationRequest {
    return UpdateProductVariationRequestFromJSONTyped(json, false);
}

export function UpdateProductVariationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProductVariationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'id': json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'] == null ? undefined : json['name'],
        'publicationDescription': json['publicationDescription'] == null ? undefined : json['publicationDescription'],
        'publicationName': json['publicationName'] == null ? undefined : json['publicationName'],
        'recurring': json['recurring'] == null ? undefined : json['recurring'],
        'status': json['status'] == null ? undefined : json['status'],
        'unitAmount': json['unitAmount'] == null ? undefined : json['unitAmount'],
    };
}

export function UpdateProductVariationRequestToJSON(json: any): UpdateProductVariationRequest {
    return UpdateProductVariationRequestToJSONTyped(json, false);
}

export function UpdateProductVariationRequestToJSONTyped(value?: UpdateProductVariationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'currency': value['currency'],
        'id': value['id'],
        'metadata': value['metadata'],
        'name': value['name'],
        'publicationDescription': value['publicationDescription'],
        'publicationName': value['publicationName'],
        'recurring': value['recurring'],
        'status': value['status'],
        'unitAmount': value['unitAmount'],
    };
}

