/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolicyActionPatternRequest } from './PolicyActionPatternRequest';
import {
    PolicyActionPatternRequestFromJSON,
    PolicyActionPatternRequestFromJSONTyped,
    PolicyActionPatternRequestToJSON,
    PolicyActionPatternRequestToJSONTyped,
} from './PolicyActionPatternRequest';
import type { RemovePolicyActionPatternRequest } from './RemovePolicyActionPatternRequest';
import {
    RemovePolicyActionPatternRequestFromJSON,
    RemovePolicyActionPatternRequestFromJSONTyped,
    RemovePolicyActionPatternRequestToJSON,
    RemovePolicyActionPatternRequestToJSONTyped,
} from './RemovePolicyActionPatternRequest';
import type { PolicyActionRequest } from './PolicyActionRequest';
import {
    PolicyActionRequestFromJSON,
    PolicyActionRequestFromJSONTyped,
    PolicyActionRequestToJSON,
    PolicyActionRequestToJSONTyped,
} from './PolicyActionRequest';

/**
 * Request to update a custom policy
 * @export
 * @interface UpdatePolicyRequest
 */
export interface UpdatePolicyRequest {
    /**
     * 
     * @type {Array<PolicyActionPatternRequest>}
     * @memberof UpdatePolicyRequest
     */
    actionPatternsToAdd?: Array<PolicyActionPatternRequest>;
    /**
     * 
     * @type {Array<RemovePolicyActionPatternRequest>}
     * @memberof UpdatePolicyRequest
     */
    actionPatternsToRemove?: Array<RemovePolicyActionPatternRequest>;
    /**
     * 
     * @type {Array<PolicyActionRequest>}
     * @memberof UpdatePolicyRequest
     */
    actionsToAdd?: Array<PolicyActionRequest>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdatePolicyRequest
     */
    actionsToRemove?: Array<string>;
    /**
     * Policy description
     * @type {string}
     * @memberof UpdatePolicyRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the UpdatePolicyRequest interface.
 */
export function instanceOfUpdatePolicyRequest(value: object): value is UpdatePolicyRequest {
    return true;
}

export function UpdatePolicyRequestFromJSON(json: any): UpdatePolicyRequest {
    return UpdatePolicyRequestFromJSONTyped(json, false);
}

export function UpdatePolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePolicyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'actionPatternsToAdd': json['actionPatternsToAdd'] == null ? undefined : ((json['actionPatternsToAdd'] as Array<any>).map(PolicyActionPatternRequestFromJSON)),
        'actionPatternsToRemove': json['actionPatternsToRemove'] == null ? undefined : ((json['actionPatternsToRemove'] as Array<any>).map(RemovePolicyActionPatternRequestFromJSON)),
        'actionsToAdd': json['actionsToAdd'] == null ? undefined : ((json['actionsToAdd'] as Array<any>).map(PolicyActionRequestFromJSON)),
        'actionsToRemove': json['actionsToRemove'] == null ? undefined : json['actionsToRemove'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdatePolicyRequestToJSON(json: any): UpdatePolicyRequest {
    return UpdatePolicyRequestToJSONTyped(json, false);
}

export function UpdatePolicyRequestToJSONTyped(value?: UpdatePolicyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actionPatternsToAdd': value['actionPatternsToAdd'] == null ? undefined : ((value['actionPatternsToAdd'] as Array<any>).map(PolicyActionPatternRequestToJSON)),
        'actionPatternsToRemove': value['actionPatternsToRemove'] == null ? undefined : ((value['actionPatternsToRemove'] as Array<any>).map(RemovePolicyActionPatternRequestToJSON)),
        'actionsToAdd': value['actionsToAdd'] == null ? undefined : ((value['actionsToAdd'] as Array<any>).map(PolicyActionRequestToJSON)),
        'actionsToRemove': value['actionsToRemove'],
        'description': value['description'],
    };
}

