/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User message content
 * @export
 * @interface UserMessage
 */
export interface UserMessage {
    /**
     * 
     * @type {Date}
     * @memberof UserMessage
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserMessage
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserMessage
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof UserMessage
     */
    userId: string;
}

/**
 * Check if a given object implements the UserMessage interface.
 */
export function instanceOfUserMessage(value: object): value is UserMessage {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UserMessageFromJSON(json: any): UserMessage {
    return UserMessageFromJSONTyped(json, false);
}

export function UserMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'text': json['text'],
        'userId': json['user_id'],
    };
}

export function UserMessageToJSON(json: any): UserMessage {
    return UserMessageToJSONTyped(json, false);
}

export function UserMessageToJSONTyped(value?: UserMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'text': value['text'],
        'user_id': value['userId'],
    };
}

