/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum AgentBuiltinToolType {
    #[serde(rename = "builtin")]
    Builtin,
}

impl std::fmt::Display for AgentBuiltinToolType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Builtin => write!(f, "builtin"),
        }
    }
}

impl Default for AgentBuiltinToolType {
    fn default() -> AgentBuiltinToolType {
        Self::Builtin
    }
}
