/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentChunkEventOneOf2 : Tool execution result
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentChunkEventOneOf2 {
    #[serde(rename = "is_finished")]
    pub is_finished: bool,
    #[serde(rename = "result")]
    pub result: String,
    #[serde(rename = "tool_id")]
    pub tool_id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AgentChunkEventOneOf2 {
    /// Tool execution result
    pub fn new(
        is_finished: bool,
        result: String,
        tool_id: String,
        r#type: Type,
    ) -> AgentChunkEventOneOf2 {
        AgentChunkEventOneOf2 {
            is_finished,
            result,
            tool_id,
            r#type,
        }
    }
}
///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum Type {
    #[serde(rename = "tool_result")]
    ToolResult,
}

impl Default for Type {
    fn default() -> Type {
        Self::ToolResult
    }
}
