/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentToolAccessRequest {
    #[serde(rename = "agent_protocol", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub agent_protocol: Option<Option<bool>>,
    #[serde(rename = "coding_agent_job", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub coding_agent_job: Option<Option<bool>>,
    #[serde(rename = "command", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub command: Option<Option<bool>>,
    #[serde(rename = "filesystem", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub filesystem: Option<Option<bool>>,
    /// Enable the `execute_sub_agent` tool for spawning child agents.
    #[serde(rename = "sub_agent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sub_agent: Option<Option<bool>>,
    /// Enable the `fetch_url` URL scraping tool (Firecrawl API).
    #[serde(rename = "url_fetch", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url_fetch: Option<Option<bool>>,
    /// Enable the `search_with_llm` web search tool (Google Custom Search).
    #[serde(rename = "web_search", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub web_search: Option<Option<bool>>,
}

impl AgentToolAccessRequest {
    pub fn new() -> AgentToolAccessRequest {
        AgentToolAccessRequest {
            agent_protocol: None,
            coding_agent_job: None,
            command: None,
            filesystem: None,
            sub_agent: None,
            url_fetch: None,
            web_search: None,
        }
    }
}

