/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentChunkEventOneOf5 : Say/text content
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentChunkEventOneOf5 {
    #[serde(rename = "index")]
    pub index: i32,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AgentChunkEventOneOf5 {
    /// Say/text content
    pub fn new(
        index: i32,
        text: String,
        r#type: Type,
    ) -> AgentChunkEventOneOf5 {
        AgentChunkEventOneOf5 {
            index,
            text,
            r#type,
        }
    }
}
///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum Type {
    #[serde(rename = "say")]
    Say,
}

impl Default for Type {
    fn default() -> Type {
        Self::Say
    }
}
