/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiKeyResponse : Response for an API key
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyResponse {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "serviceAccountId")]
    pub service_account_id: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl ApiKeyResponse {
    /// Response for an API key
    pub fn new(
        created_at: String,
        id: String,
        name: String,
        service_account_id: String,
        value: String,
    ) -> ApiKeyResponse {
        ApiKeyResponse {
            created_at,
            id,
            name,
            service_account_id,
            value,
        }
    }
}
