/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateObjectMappingRequest : Request to create an object mapping
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateObjectMappingRequest {
    /// Internal entity ID
    #[serde(rename = "entityId")]
    pub entity_id: String,
    /// Object type name
    #[serde(rename = "objectName")]
    pub object_name: String,
    /// Provider name (e.g., \"HubSpot\")
    #[serde(rename = "providerName")]
    pub provider_name: String,
    /// External provider object ID
    #[serde(rename = "providerObjectId")]
    pub provider_object_id: String,
}

impl CreateObjectMappingRequest {
    /// Request to create an object mapping
    pub fn new(entity_id: String, object_name: String, provider_name: String, provider_object_id: String) -> CreateObjectMappingRequest {
        CreateObjectMappingRequest {
            entity_id,
            object_name,
            provider_name,
            provider_object_id,
        }
    }
}

