/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserResponse {
    #[serde(rename = "user")]
    pub user: Box<models::User>,
}

impl CreateUserResponse {
    pub fn new(user: models::User) -> CreateUserResponse {
        CreateUserResponse {
            user: Box::new(user),
        }
    }
}
