/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateClientResponse : Response for newly created OAuth2 client (includes plain-text secret)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateClientResponse {
    #[serde(rename = "allowedScopes")]
    pub allowed_scopes: Vec<String>,
    #[serde(rename = "clientId")]
    pub client_id: String,
    #[serde(rename = "clientSecret")]
    pub client_secret: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "grantTypes")]
    pub grant_types: Vec<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "redirectUris")]
    pub redirect_uris: Vec<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "useTachyonUserPool")]
    pub use_tachyon_user_pool: bool,
}

impl CreateClientResponse {
    /// Response for newly created OAuth2 client (includes plain-text secret)
    pub fn new(allowed_scopes: Vec<String>, client_id: String, client_secret: String, created_at: String, grant_types: Vec<String>, id: String, name: String, redirect_uris: Vec<String>, status: String, use_tachyon_user_pool: bool) -> CreateClientResponse {
        CreateClientResponse {
            allowed_scopes,
            client_id,
            client_secret,
            created_at,
            grant_types,
            id,
            name,
            redirect_uris,
            status,
            use_tachyon_user_pool,
        }
    }
}

