/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateProductRequest : Request body for creating a product
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProductRequest {
    /// Billing cycle: MONTHLY, YEARLY, ONE_TIME
    #[serde(rename = "billingCycle")]
    pub billing_cycle: String,
    /// Whether to sync with CRM
    #[serde(rename = "createCrm", skip_serializing_if = "Option::is_none")]
    pub create_crm: Option<bool>,
    /// Product description
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// Optional product ID (auto-generated if omitted)
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    /// File IDs for product images
    #[serde(
        rename = "imageFileIds",
        skip_serializing_if = "Option::is_none"
    )]
    pub image_file_ids: Option<Vec<String>>,
    /// JAN code
    #[serde(
        rename = "janCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub jan_code: Option<Option<String>>,
    /// Product type: PLAN or PRODUCT
    #[serde(rename = "kind")]
    pub kind: String,
    /// List price in smallest currency unit
    #[serde(rename = "listPrice")]
    pub list_price: i32,
    /// Product name
    #[serde(rename = "name")]
    pub name: String,
    /// Publication display description
    #[serde(
        rename = "publicationDescription",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub publication_description: Option<Option<String>>,
    /// Publication display name
    #[serde(
        rename = "publicationName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub publication_name: Option<Option<String>>,
    /// Publication status
    #[serde(
        rename = "publicationStatus",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub publication_status: Option<Option<String>>,
    /// SKU code
    #[serde(
        rename = "skuCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sku_code: Option<Option<String>>,
    /// Product status: DRAFT, ACTIVE, ARCHIVED
    #[serde(rename = "status")]
    pub status: String,
    /// UPC code
    #[serde(
        rename = "upcCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub upc_code: Option<Option<String>>,
    /// Product variations
    #[serde(
        rename = "variations",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub variations: Option<Option<Vec<models::ProductVariationRequest>>>,
}

impl CreateProductRequest {
    /// Request body for creating a product
    pub fn new(
        billing_cycle: String,
        kind: String,
        list_price: i32,
        name: String,
        status: String,
    ) -> CreateProductRequest {
        CreateProductRequest {
            billing_cycle,
            create_crm: None,
            description: None,
            id: None,
            image_file_ids: None,
            jan_code: None,
            kind,
            list_price,
            name,
            publication_description: None,
            publication_name: None,
            publication_status: None,
            sku_code: None,
            status,
            upc_code: None,
            variations: None,
        }
    }
}
