/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteOperatorResponse : Response for deleting an operator
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteOperatorResponse {
    #[serde(rename = "success")]
    pub success: bool,
}

impl DeleteOperatorResponse {
    /// Response for deleting an operator
    pub fn new(success: bool) -> DeleteOperatorResponse {
        DeleteOperatorResponse {
            success,
        }
    }
}

