/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeltaMessage {
    /// The content of the message
    #[serde(rename = "content", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content: Option<Option<String>>,
    /// The role of the message author
    #[serde(rename = "role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role: Option<Option<models::ChatRole>>,
    /// The tool calls
    #[serde(rename = "tool_calls", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Option<Vec<models::ToolCall>>>,
}

impl DeltaMessage {
    pub fn new() -> DeltaMessage {
        DeltaMessage {
            content: None,
            role: None,
            tool_calls: None,
        }
    }
}

