/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorResponse : Common error response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// Error message
    #[serde(rename = "message")]
    pub message: String,
}

impl ErrorResponse {
    /// Common error response
    pub fn new(message: String) -> ErrorResponse {
        ErrorResponse {
            message,
        }
    }
}

