/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueQuoteRequest : Request body for issuing a quote
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueQuoteRequest {
    /// Client ID to issue the quote to
    #[serde(rename = "clientId")]
    pub client_id: String,
}

impl IssueQuoteRequest {
    /// Request body for issuing a quote
    pub fn new(client_id: String) -> IssueQuoteRequest {
        IssueQuoteRequest { client_id }
    }
}
