/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelInfo {
    #[serde(rename = "context_window", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub context_window: Option<Option<i32>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "max_output_tokens", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_output_tokens: Option<Option<i32>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "supported_features")]
    pub supported_features: Vec<String>,
}

impl ModelInfo {
    pub fn new(id: String, name: String, provider: String, supported_features: Vec<String>) -> ModelInfo {
        ModelInfo {
            context_window: None,
            description: None,
            id,
            max_output_tokens: None,
            name,
            provider,
            supported_features,
        }
    }
}

