/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsResponse {
    #[serde(rename = "models")]
    pub models: Vec<models::ModelInfo>,
    #[serde(rename = "total_count")]
    pub total_count: i32,
}

impl ModelsResponse {
    pub fn new(models: Vec<models::ModelInfo>, total_count: i32) -> ModelsResponse {
        ModelsResponse {
            models,
            total_count,
        }
    }
}

