/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuthTokenDetailResponse : Response for OAuth token detail
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthTokenDetailResponse {
    #[serde(rename = "accessToken")]
    pub access_token: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "providerUserId")]
    pub provider_user_id: String,
    #[serde(
        rename = "refreshToken",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub refresh_token: Option<Option<String>>,
}

impl OAuthTokenDetailResponse {
    /// Response for OAuth token detail
    pub fn new(
        access_token: String,
        expires_at: String,
        provider: String,
        provider_user_id: String,
    ) -> OAuthTokenDetailResponse {
        OAuthTokenDetailResponse {
            access_token,
            expires_at,
            provider,
            provider_user_id,
            refresh_token: None,
        }
    }
}
