/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartOneOf1 {
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl PartOneOf1 {
    pub fn new(image: String, r#type: Type) -> PartOneOf1 {
        PartOneOf1 {
            image,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "image")]
    Image,
}

impl Default for Type {
    fn default() -> Type {
        Self::Image
    }
}

