/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PolicyActionRequest : Policy action entry
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PolicyActionRequest {
    /// Action full name
    #[serde(rename = "actionFullName")]
    pub action_full_name: String,
    /// Policy effect. Supported values are \"allow\" and \"deny\"
    #[serde(rename = "effect")]
    pub effect: String,
}

impl PolicyActionRequest {
    /// Policy action entry
    pub fn new(action_full_name: String, effect: String) -> PolicyActionRequest {
        PolicyActionRequest {
            action_full_name,
            effect,
        }
    }
}

