/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecurringRevenueRequest : Request body for calculating recurring revenue
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecurringRevenueRequest {
    /// Period end date (YYYY-MM-DD)
    #[serde(rename = "endDate")]
    pub end_date: String,
    /// Revenue cycle: WEEKLY or MONTHLY
    #[serde(rename = "revenueCycle")]
    pub revenue_cycle: String,
    /// Period start date (YYYY-MM-DD)
    #[serde(rename = "startDate")]
    pub start_date: String,
}

impl RecurringRevenueRequest {
    /// Request body for calculating recurring revenue
    pub fn new(
        end_date: String,
        revenue_cycle: String,
        start_date: String,
    ) -> RecurringRevenueRequest {
        RecurringRevenueRequest {
            end_date,
            revenue_cycle,
            start_date,
        }
    }
}
