/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShippingDestinationResponse : Shipping destination response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShippingDestinationResponse {
    /// Shipping destination ID
    #[serde(rename = "id")]
    pub id: String,
}

impl ShippingDestinationResponse {
    /// Shipping destination response
    pub fn new(id: String) -> ShippingDestinationResponse {
        ShippingDestinationResponse {
            id,
        }
    }
}

