/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignInWithPlatformRequest {
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(rename = "allow_sign_up", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allow_sign_up: Option<Option<bool>>,
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "platform_id")]
    pub platform_id: String,
}

impl SignInWithPlatformRequest {
    pub fn new(access_token: String, platform_id: String) -> SignInWithPlatformRequest {
        SignInWithPlatformRequest {
            access_token,
            allow_sign_up: None,
            email: None,
            name: None,
            platform_id,
        }
    }
}

