/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.51.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateUserRoleRequest : Request DTO for updating user role
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserRoleRequest {
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
}

impl UpdateUserRoleRequest {
    /// Request DTO for updating user role
    pub fn new(role: String, tenant_id: String) -> UpdateUserRoleRequest {
        UpdateUserRoleRequest {
            role,
            tenant_id,
        }
    }
}

