/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateClientRequest : Request to update an OAuth2 client
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateClientRequest {
    /// Allowed scopes
    #[serde(rename = "allowedScopes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allowed_scopes: Option<Option<Vec<String>>>,
    /// Display name
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// Allowed redirect URIs
    #[serde(rename = "redirectUris", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub redirect_uris: Option<Option<Vec<String>>>,
    /// Status: \"active\" or \"inactive\"
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
}

impl UpdateClientRequest {
    /// Request to update an OAuth2 client
    pub fn new() -> UpdateClientRequest {
        UpdateClientRequest {
            allowed_scopes: None,
            name: None,
            redirect_uris: None,
            status: None,
        }
    }
}

