/*
 * Tachyon API
 *
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserListResponse : Response DTO for user list
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserListResponse {
    #[serde(rename = "users")]
    pub users: Vec<models::UserResponse>,
}

impl UserListResponse {
    /// Response DTO for user list
    pub fn new(users: Vec<models::UserResponse>) -> UserListResponse {
        UserListResponse { users }
    }
}
