/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgentChunk,
  AgentExecuteRequest,
  AgentMessagesResponse,
  AgentStatusResponse,
  CreateAgentSessionOutputData,
  CreateAgentSessionRequest,
  ListAgentSessionsOutputData,
  ToolResultSubmission,
} from '../models/index';
import {
    AgentChunkFromJSON,
    AgentChunkToJSON,
    AgentExecuteRequestFromJSON,
    AgentExecuteRequestToJSON,
    AgentMessagesResponseFromJSON,
    AgentMessagesResponseToJSON,
    AgentStatusResponseFromJSON,
    AgentStatusResponseToJSON,
    CreateAgentSessionOutputDataFromJSON,
    CreateAgentSessionOutputDataToJSON,
    CreateAgentSessionRequestFromJSON,
    CreateAgentSessionRequestToJSON,
    ListAgentSessionsOutputDataFromJSON,
    ListAgentSessionsOutputDataToJSON,
    ToolResultSubmissionFromJSON,
    ToolResultSubmissionToJSON,
} from '../models/index';

export interface CreateAgentSessionOperationRequest {
    xOperatorId: string;
    authorization: string;
    createAgentSessionRequest: CreateAgentSessionRequest;
}

export interface ExecuteAgentRequest {
    chatroomId: string;
    xOperatorId: string;
    authorization: string;
    agentExecuteRequest: AgentExecuteRequest;
}

export interface ExecuteAgentSessionRequest {
    sessionId: string;
    xOperatorId: string;
    authorization: string;
    agentExecuteRequest: AgentExecuteRequest;
}

export interface GetAgentMessagesRequest {
    chatroomId: string;
    xOperatorId: string;
    authorization: string;
    limit?: number | null;
    offset?: number | null;
}

export interface GetAgentMessagesSessionRequest {
    sessionId: string;
    xOperatorId: string;
    authorization: string;
    limit?: number | null;
    offset?: number | null;
}

export interface GetAgentStatusRequest {
    chatroomId: string;
    xOperatorId: string;
    authorization: string;
}

export interface GetAgentStatusSessionRequest {
    sessionId: string;
    xOperatorId: string;
    authorization: string;
}

export interface ListAgentSessionsRequest {
    xOperatorId: string;
    authorization: string;
    limit?: number | null;
    offset?: number | null;
}

export interface SubmitToolResultRequest {
    chatroomId: string;
    xOperatorId: string;
    authorization: string;
    toolResultSubmission: ToolResultSubmission;
}

export interface SubmitToolResultSessionRequest {
    sessionId: string;
    xOperatorId: string;
    authorization: string;
    toolResultSubmission: ToolResultSubmission;
}

/**
 * 
 */
export class AgentApi extends runtime.BaseAPI {

    /**
     * Creates request options for createAgentSession without sending the request
     */
    async createAgentSessionRequestOpts(requestParameters: CreateAgentSessionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xOperatorId'] == null) {
            throw new runtime.RequiredError(
                'xOperatorId',
                'Required parameter "xOperatorId" was null or undefined when calling createAgentSession().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling createAgentSession().'
            );
        }

        if (requestParameters['createAgentSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'createAgentSessionRequest',
                'Required parameter "createAgentSessionRequest" was null or undefined when calling createAgentSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOperatorId'] != null) {
            headerParameters['x-operator-id'] = String(requestParameters['xOperatorId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/llms/sessions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAgentSessionRequestToJSON(requestParameters['createAgentSessionRequest']),
        };
    }

    /**
     * Returns a session with an `as_`-prefixed ID that can be used with the session agent endpoints.
     * Create a new independent agent session.
     */
    async createAgentSessionRaw(requestParameters: CreateAgentSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAgentSessionOutputData>> {
        const requestOptions = await this.createAgentSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAgentSessionOutputDataFromJSON(jsonValue));
    }

    /**
     * Returns a session with an `as_`-prefixed ID that can be used with the session agent endpoints.
     * Create a new independent agent session.
     */
    async createAgentSession(requestParameters: CreateAgentSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAgentSessionOutputData> {
        const response = await this.createAgentSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for executeAgent without sending the request
     */
    async executeAgentRequestOpts(requestParameters: ExecuteAgentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chatroomId'] == null) {
            throw new runtime.RequiredError(
                'chatroomId',
                'Required parameter "chatroomId" was null or undefined when calling executeAgent().'
            );
        }

        if (requestParameters['xOperatorId'] == null) {
            throw new runtime.RequiredError(
                'xOperatorId',
                'Required parameter "xOperatorId" was null or undefined when calling executeAgent().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling executeAgent().'
            );
        }

        if (requestParameters['agentExecuteRequest'] == null) {
            throw new runtime.RequiredError(
                'agentExecuteRequest',
                'Required parameter "agentExecuteRequest" was null or undefined when calling executeAgent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOperatorId'] != null) {
            headerParameters['x-operator-id'] = String(requestParameters['xOperatorId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/llms/chatrooms/{chatroom_id}/agent/execute`;
        urlPath = urlPath.replace(`{${"chatroom_id"}}`, encodeURIComponent(String(requestParameters['chatroomId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AgentExecuteRequestToJSON(requestParameters['agentExecuteRequest']),
        };
    }

    /**
     * Execute a task using the agent system. Returns an SSE stream of `AgentChunk` events.  ## Client-Side Tools  You can provide custom tool definitions via the `client_tools` field. When the LLM decides to call one of these tools, the server emits a `tool_call_pending` SSE event containing the tool name, arguments, and a unique `tool_id`. The client should:  1. Execute the tool locally using the provided arguments 2. Submit the result via    `POST /v1/llms/chatrooms/{chatroom_id}/agent/tool-result`    with the matching `tool_id` 3. The agent resumes processing with the tool result  For **fire-and-forget** tools (`fire_and_forget: true`), the server immediately returns a success message to the LLM without waiting for a result submission. The client still receives the `tool_call_pending` event and can execute the tool, but does not need to submit a result.  Tool names must not collide with server built-in tools (e.g. `read_file`, `execute_command`). The server validates this and returns an error if a collision is detected.  When `client_tools` is provided, JSON tool call mode is automatically enabled — you do not need to set `use_json_tool_calls` separately.
     * Execute agent
     */
    async executeAgentRaw(requestParameters: ExecuteAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentChunk>> {
        const requestOptions = await this.executeAgentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentChunkFromJSON(jsonValue));
    }

    /**
     * Execute a task using the agent system. Returns an SSE stream of `AgentChunk` events.  ## Client-Side Tools  You can provide custom tool definitions via the `client_tools` field. When the LLM decides to call one of these tools, the server emits a `tool_call_pending` SSE event containing the tool name, arguments, and a unique `tool_id`. The client should:  1. Execute the tool locally using the provided arguments 2. Submit the result via    `POST /v1/llms/chatrooms/{chatroom_id}/agent/tool-result`    with the matching `tool_id` 3. The agent resumes processing with the tool result  For **fire-and-forget** tools (`fire_and_forget: true`), the server immediately returns a success message to the LLM without waiting for a result submission. The client still receives the `tool_call_pending` event and can execute the tool, but does not need to submit a result.  Tool names must not collide with server built-in tools (e.g. `read_file`, `execute_command`). The server validates this and returns an error if a collision is detected.  When `client_tools` is provided, JSON tool call mode is automatically enabled — you do not need to set `use_json_tool_calls` separately.
     * Execute agent
     */
    async executeAgent(requestParameters: ExecuteAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentChunk> {
        const response = await this.executeAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for executeAgentSession without sending the request
     */
    async executeAgentSessionRequestOpts(requestParameters: ExecuteAgentSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling executeAgentSession().'
            );
        }

        if (requestParameters['xOperatorId'] == null) {
            throw new runtime.RequiredError(
                'xOperatorId',
                'Required parameter "xOperatorId" was null or undefined when calling executeAgentSession().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling executeAgentSession().'
            );
        }

        if (requestParameters['agentExecuteRequest'] == null) {
            throw new runtime.RequiredError(
                'agentExecuteRequest',
                'Required parameter "agentExecuteRequest" was null or undefined when calling executeAgentSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOperatorId'] != null) {
            headerParameters['x-operator-id'] = String(requestParameters['xOperatorId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/llms/sessions/{session_id}/agent/execute`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AgentExecuteRequestToJSON(requestParameters['agentExecuteRequest']),
        };
    }

    /**
     * Accepts both independent session IDs (`as_...`) and legacy chatroom IDs (`ch_...`) for backwards compatibility.  ## Client-Side Tools  You can provide custom tool definitions via the `client_tools` field. When the LLM decides to call one of these tools, the server emits a `tool_call_pending` SSE event containing the tool name, arguments, and a unique `tool_id`. The client should:  1. Execute the tool locally using the provided arguments 2. Submit the result via    `POST /v1/llms/sessions/{session_id}/agent/tool-result`    with the matching `tool_id` 3. The agent resumes processing with the tool result  For **fire-and-forget** tools (`fire_and_forget: true`), the server immediately returns a success to the LLM without waiting for a result submission.
     * Execute agent via session endpoint.
     */
    async executeAgentSessionRaw(requestParameters: ExecuteAgentSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentChunk>> {
        const requestOptions = await this.executeAgentSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentChunkFromJSON(jsonValue));
    }

    /**
     * Accepts both independent session IDs (`as_...`) and legacy chatroom IDs (`ch_...`) for backwards compatibility.  ## Client-Side Tools  You can provide custom tool definitions via the `client_tools` field. When the LLM decides to call one of these tools, the server emits a `tool_call_pending` SSE event containing the tool name, arguments, and a unique `tool_id`. The client should:  1. Execute the tool locally using the provided arguments 2. Submit the result via    `POST /v1/llms/sessions/{session_id}/agent/tool-result`    with the matching `tool_id` 3. The agent resumes processing with the tool result  For **fire-and-forget** tools (`fire_and_forget: true`), the server immediately returns a success to the LLM without waiting for a result submission.
     * Execute agent via session endpoint.
     */
    async executeAgentSession(requestParameters: ExecuteAgentSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentChunk> {
        const response = await this.executeAgentSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAgentMessages without sending the request
     */
    async getAgentMessagesRequestOpts(requestParameters: GetAgentMessagesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chatroomId'] == null) {
            throw new runtime.RequiredError(
                'chatroomId',
                'Required parameter "chatroomId" was null or undefined when calling getAgentMessages().'
            );
        }

        if (requestParameters['xOperatorId'] == null) {
            throw new runtime.RequiredError(
                'xOperatorId',
                'Required parameter "xOperatorId" was null or undefined when calling getAgentMessages().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getAgentMessages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOperatorId'] != null) {
            headerParameters['x-operator-id'] = String(requestParameters['xOperatorId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/llms/chatrooms/{chatroom_id}/agent/messages`;
        urlPath = urlPath.replace(`{${"chatroom_id"}}`, encodeURIComponent(String(requestParameters['chatroomId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get agent message log for specified chatroom.
     * Get agent message log
     */
    async getAgentMessagesRaw(requestParameters: GetAgentMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentMessagesResponse>> {
        const requestOptions = await this.getAgentMessagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentMessagesResponseFromJSON(jsonValue));
    }

    /**
     * Get agent message log for specified chatroom.
     * Get agent message log
     */
    async getAgentMessages(requestParameters: GetAgentMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentMessagesResponse> {
        const response = await this.getAgentMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAgentMessagesSession without sending the request
     */
    async getAgentMessagesSessionRequestOpts(requestParameters: GetAgentMessagesSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getAgentMessagesSession().'
            );
        }

        if (requestParameters['xOperatorId'] == null) {
            throw new runtime.RequiredError(
                'xOperatorId',
                'Required parameter "xOperatorId" was null or undefined when calling getAgentMessagesSession().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getAgentMessagesSession().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOperatorId'] != null) {
            headerParameters['x-operator-id'] = String(requestParameters['xOperatorId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/llms/sessions/{session_id}/agent/messages`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Session-based alias of `GET /v1/llms/chatrooms/{chatroom_id}/agent/messages`.
     * Get agent message log (session alias)
     */
    async getAgentMessagesSessionRaw(requestParameters: GetAgentMessagesSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentMessagesResponse>> {
        const requestOptions = await this.getAgentMessagesSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentMessagesResponseFromJSON(jsonValue));
    }

    /**
     * Session-based alias of `GET /v1/llms/chatrooms/{chatroom_id}/agent/messages`.
     * Get agent message log (session alias)
     */
    async getAgentMessagesSession(requestParameters: GetAgentMessagesSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentMessagesResponse> {
        const response = await this.getAgentMessagesSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAgentStatus without sending the request
     */
    async getAgentStatusRequestOpts(requestParameters: GetAgentStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chatroomId'] == null) {
            throw new runtime.RequiredError(
                'chatroomId',
                'Required parameter "chatroomId" was null or undefined when calling getAgentStatus().'
            );
        }

        if (requestParameters['xOperatorId'] == null) {
            throw new runtime.RequiredError(
                'xOperatorId',
                'Required parameter "xOperatorId" was null or undefined when calling getAgentStatus().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getAgentStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOperatorId'] != null) {
            headerParameters['x-operator-id'] = String(requestParameters['xOperatorId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/llms/chatrooms/{chatroom_id}/agent/status`;
        urlPath = urlPath.replace(`{${"chatroom_id"}}`, encodeURIComponent(String(requestParameters['chatroomId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get execution status of agent for specified chatroom.
     * Get agent status
     */
    async getAgentStatusRaw(requestParameters: GetAgentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentStatusResponse>> {
        const requestOptions = await this.getAgentStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentStatusResponseFromJSON(jsonValue));
    }

    /**
     * Get execution status of agent for specified chatroom.
     * Get agent status
     */
    async getAgentStatus(requestParameters: GetAgentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentStatusResponse> {
        const response = await this.getAgentStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAgentStatusSession without sending the request
     */
    async getAgentStatusSessionRequestOpts(requestParameters: GetAgentStatusSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getAgentStatusSession().'
            );
        }

        if (requestParameters['xOperatorId'] == null) {
            throw new runtime.RequiredError(
                'xOperatorId',
                'Required parameter "xOperatorId" was null or undefined when calling getAgentStatusSession().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getAgentStatusSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOperatorId'] != null) {
            headerParameters['x-operator-id'] = String(requestParameters['xOperatorId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/llms/sessions/{session_id}/agent/status`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Session-based alias of `GET /v1/llms/chatrooms/{chatroom_id}/agent/status`.
     * Get agent status (session alias)
     */
    async getAgentStatusSessionRaw(requestParameters: GetAgentStatusSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentStatusResponse>> {
        const requestOptions = await this.getAgentStatusSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentStatusResponseFromJSON(jsonValue));
    }

    /**
     * Session-based alias of `GET /v1/llms/chatrooms/{chatroom_id}/agent/status`.
     * Get agent status (session alias)
     */
    async getAgentStatusSession(requestParameters: GetAgentStatusSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentStatusResponse> {
        const response = await this.getAgentStatusSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAgentSessions without sending the request
     */
    async listAgentSessionsRequestOpts(requestParameters: ListAgentSessionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xOperatorId'] == null) {
            throw new runtime.RequiredError(
                'xOperatorId',
                'Required parameter "xOperatorId" was null or undefined when calling listAgentSessions().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling listAgentSessions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOperatorId'] != null) {
            headerParameters['x-operator-id'] = String(requestParameters['xOperatorId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/llms/sessions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List agent sessions for the current tenant.
     */
    async listAgentSessionsRaw(requestParameters: ListAgentSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListAgentSessionsOutputData>> {
        const requestOptions = await this.listAgentSessionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListAgentSessionsOutputDataFromJSON(jsonValue));
    }

    /**
     * List agent sessions for the current tenant.
     */
    async listAgentSessions(requestParameters: ListAgentSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListAgentSessionsOutputData> {
        const response = await this.listAgentSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submitToolResult without sending the request
     */
    async submitToolResultRequestOpts(requestParameters: SubmitToolResultRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chatroomId'] == null) {
            throw new runtime.RequiredError(
                'chatroomId',
                'Required parameter "chatroomId" was null or undefined when calling submitToolResult().'
            );
        }

        if (requestParameters['xOperatorId'] == null) {
            throw new runtime.RequiredError(
                'xOperatorId',
                'Required parameter "xOperatorId" was null or undefined when calling submitToolResult().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling submitToolResult().'
            );
        }

        if (requestParameters['toolResultSubmission'] == null) {
            throw new runtime.RequiredError(
                'toolResultSubmission',
                'Required parameter "toolResultSubmission" was null or undefined when calling submitToolResult().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOperatorId'] != null) {
            headerParameters['x-operator-id'] = String(requestParameters['xOperatorId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/llms/chatrooms/{chatroom_id}/agent/tool-result`;
        urlPath = urlPath.replace(`{${"chatroom_id"}}`, encodeURIComponent(String(requestParameters['chatroomId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ToolResultSubmissionToJSON(requestParameters['toolResultSubmission']),
        };
    }

    /**
     * After receiving a `tool_call_pending` SSE event from the agent execute stream, call this endpoint with the matching `tool_id` and the tool execution result.  The agent is blocked waiting for this result (up to 5 minutes). Once submitted, the agent resumes processing with the provided output.  For **fire-and-forget** tools, this endpoint does not need to be called — the agent continues immediately. If called anyway, the server returns 404 (no pending tool call).  ## Flow  1. Client sends `POST /agent/execute` with `client_tools` 2. Server streams SSE events; emits `tool_call_pending`    when the LLM calls a client tool 3. Client executes the tool locally 4. Client calls this endpoint with the result 5. Server delivers the result to the agent and resumes
     * Submit the result for a client-side tool call.
     */
    async submitToolResultRaw(requestParameters: SubmitToolResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.submitToolResultRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * After receiving a `tool_call_pending` SSE event from the agent execute stream, call this endpoint with the matching `tool_id` and the tool execution result.  The agent is blocked waiting for this result (up to 5 minutes). Once submitted, the agent resumes processing with the provided output.  For **fire-and-forget** tools, this endpoint does not need to be called — the agent continues immediately. If called anyway, the server returns 404 (no pending tool call).  ## Flow  1. Client sends `POST /agent/execute` with `client_tools` 2. Server streams SSE events; emits `tool_call_pending`    when the LLM calls a client tool 3. Client executes the tool locally 4. Client calls this endpoint with the result 5. Server delivers the result to the agent and resumes
     * Submit the result for a client-side tool call.
     */
    async submitToolResult(requestParameters: SubmitToolResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.submitToolResultRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submitToolResultSession without sending the request
     */
    async submitToolResultSessionRequestOpts(requestParameters: SubmitToolResultSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling submitToolResultSession().'
            );
        }

        if (requestParameters['xOperatorId'] == null) {
            throw new runtime.RequiredError(
                'xOperatorId',
                'Required parameter "xOperatorId" was null or undefined when calling submitToolResultSession().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling submitToolResultSession().'
            );
        }

        if (requestParameters['toolResultSubmission'] == null) {
            throw new runtime.RequiredError(
                'toolResultSubmission',
                'Required parameter "toolResultSubmission" was null or undefined when calling submitToolResultSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOperatorId'] != null) {
            headerParameters['x-operator-id'] = String(requestParameters['xOperatorId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/llms/sessions/{session_id}/agent/tool-result`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ToolResultSubmissionToJSON(requestParameters['toolResultSubmission']),
        };
    }

    /**
     * Session-based alias of `POST /v1/llms/chatrooms/{chatroom_id}/agent/tool-result`.
     * Submit client tool result (session alias)
     */
    async submitToolResultSessionRaw(requestParameters: SubmitToolResultSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.submitToolResultSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Session-based alias of `POST /v1/llms/chatrooms/{chatroom_id}/agent/tool-result`.
     * Submit client tool result (session alias)
     */
    async submitToolResultSession(requestParameters: SubmitToolResultSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.submitToolResultSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
