/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ActionListResponse,
  EvaluatePoliciesBatchRequest,
  EvaluatePoliciesBatchResponse,
  PolicyResponse,
} from '../models/index';
import {
    ActionListResponseFromJSON,
    ActionListResponseToJSON,
    EvaluatePoliciesBatchRequestFromJSON,
    EvaluatePoliciesBatchRequestToJSON,
    EvaluatePoliciesBatchResponseFromJSON,
    EvaluatePoliciesBatchResponseToJSON,
    PolicyResponseFromJSON,
    PolicyResponseToJSON,
} from '../models/index';

export interface EvaluatePoliciesBatchOperationRequest {
    evaluatePoliciesBatchRequest: EvaluatePoliciesBatchRequest;
}

export interface GetPolicyRequest {
    id: string;
}

export interface ListActionsRequest {
    context?: string | null;
}

/**
 * 
 */
export class AuthPoliciesApi extends runtime.BaseAPI {

    /**
     * Creates request options for evaluatePoliciesBatch without sending the request
     */
    async evaluatePoliciesBatchRequestOpts(requestParameters: EvaluatePoliciesBatchOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['evaluatePoliciesBatchRequest'] == null) {
            throw new runtime.RequiredError(
                'evaluatePoliciesBatchRequest',
                'Required parameter "evaluatePoliciesBatchRequest" was null or undefined when calling evaluatePoliciesBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/policies/check`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EvaluatePoliciesBatchRequestToJSON(requestParameters['evaluatePoliciesBatchRequest']),
        };
    }

    /**
     * Evaluate multiple policy actions in batch
     */
    async evaluatePoliciesBatchRaw(requestParameters: EvaluatePoliciesBatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EvaluatePoliciesBatchResponse>> {
        const requestOptions = await this.evaluatePoliciesBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EvaluatePoliciesBatchResponseFromJSON(jsonValue));
    }

    /**
     * Evaluate multiple policy actions in batch
     */
    async evaluatePoliciesBatch(requestParameters: EvaluatePoliciesBatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EvaluatePoliciesBatchResponse> {
        const response = await this.evaluatePoliciesBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPolicy without sending the request
     */
    async getPolicyRequestOpts(requestParameters: GetPolicyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPolicy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/policies/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a policy by ID
     */
    async getPolicyRaw(requestParameters: GetPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolicyResponse>> {
        const requestOptions = await this.getPolicyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PolicyResponseFromJSON(jsonValue));
    }

    /**
     * Get a policy by ID
     */
    async getPolicy(requestParameters: GetPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolicyResponse> {
        const response = await this.getPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listActions without sending the request
     */
    async listActionsRequestOpts(requestParameters: ListActionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['context'] != null) {
            queryParameters['context'] = requestParameters['context'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/actions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all registered actions
     */
    async listActionsRaw(requestParameters: ListActionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ActionListResponse>> {
        const requestOptions = await this.listActionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActionListResponseFromJSON(jsonValue));
    }

    /**
     * List all registered actions
     */
    async listActions(requestParameters: ListActionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ActionListResponse> {
        const response = await this.listActionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
