/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.58.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConsentListResponse,
} from '../models/index';
import {
    ConsentListResponseFromJSON,
    ConsentListResponseToJSON,
} from '../models/index';

export interface RevokeConsentRequest {
    id: string;
}

/**
 * 
 */
export class AuthOAuth2ConsentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for listConsents without sending the request
     */
    async listConsentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/consents`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all consents for the authenticated user.
     * GET /v1/auth/consents
     */
    async listConsentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsentListResponse>> {
        const requestOptions = await this.listConsentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsentListResponseFromJSON(jsonValue));
    }

    /**
     * List all consents for the authenticated user.
     * GET /v1/auth/consents
     */
    async listConsents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsentListResponse> {
        const response = await this.listConsentsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeConsent without sending the request
     */
    async revokeConsentRequestOpts(requestParameters: RevokeConsentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling revokeConsent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/consents/{id}/revoke`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke a user consent by ID.
     * POST /v1/auth/consents/:id/revoke
     */
    async revokeConsentRaw(requestParameters: RevokeConsentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.revokeConsentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke a user consent by ID.
     * POST /v1/auth/consents/:id/revoke
     */
    async revokeConsent(requestParameters: RevokeConsentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeConsentRaw(requestParameters, initOverrides);
    }

}
