/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateShippingDestinationRequest,
  ErrorResponse,
  ShippingAvailabilityResponse,
  ShippingDestinationResponse,
} from '../models/index';
import {
    CreateShippingDestinationRequestFromJSON,
    CreateShippingDestinationRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ShippingAvailabilityResponseFromJSON,
    ShippingAvailabilityResponseToJSON,
    ShippingDestinationResponseFromJSON,
    ShippingDestinationResponseToJSON,
} from '../models/index';

export interface CheckShippingAvailabilityRequest {
    id: string;
}

export interface CreateShippingDestinationOperationRequest {
    createShippingDestinationRequest: CreateShippingDestinationRequest;
}

/**
 * 
 */
export class DeliveryShippingApi extends runtime.BaseAPI {

    /**
     * Creates request options for checkShippingAvailability without sending the request
     */
    async checkShippingAvailabilityRequestOpts(requestParameters: CheckShippingAvailabilityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling checkShippingAvailability().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/delivery/shipping-destinations/{id}/availability`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check physical shipping availability
     */
    async checkShippingAvailabilityRaw(requestParameters: CheckShippingAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShippingAvailabilityResponse>> {
        const requestOptions = await this.checkShippingAvailabilityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShippingAvailabilityResponseFromJSON(jsonValue));
    }

    /**
     * Check physical shipping availability
     */
    async checkShippingAvailability(requestParameters: CheckShippingAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShippingAvailabilityResponse> {
        const response = await this.checkShippingAvailabilityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createShippingDestination without sending the request
     */
    async createShippingDestinationRequestOpts(requestParameters: CreateShippingDestinationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createShippingDestinationRequest'] == null) {
            throw new runtime.RequiredError(
                'createShippingDestinationRequest',
                'Required parameter "createShippingDestinationRequest" was null or undefined when calling createShippingDestination().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/delivery/shipping-destinations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateShippingDestinationRequestToJSON(requestParameters['createShippingDestinationRequest']),
        };
    }

    /**
     * Create a shipping destination
     */
    async createShippingDestinationRaw(requestParameters: CreateShippingDestinationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShippingDestinationResponse>> {
        const requestOptions = await this.createShippingDestinationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShippingDestinationResponseFromJSON(jsonValue));
    }

    /**
     * Create a shipping destination
     */
    async createShippingDestination(requestParameters: CreateShippingDestinationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShippingDestinationResponse> {
        const response = await this.createShippingDestinationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
