/* tslint:disable */
/* eslint-disable */
/**
 * Tachyon API
 * Tachyon Platform REST API
 *
 * The version of the OpenAPI document: 0.49.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ProviderListResponse,
  StripeCustomerRequest,
  StripeCustomerResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ProviderListResponseFromJSON,
    ProviderListResponseToJSON,
    StripeCustomerRequestFromJSON,
    StripeCustomerRequestToJSON,
    StripeCustomerResponseFromJSON,
    StripeCustomerResponseToJSON,
} from '../models/index';

export interface GetOrCreateStripeCustomerRequest {
    stripeCustomerRequest: StripeCustomerRequest;
}

export interface ListProvidersRequest {
    entityId: string;
}

/**
 * 
 */
export class PaymentApi extends runtime.BaseAPI {

    /**
     * Creates request options for getOrCreateStripeCustomer without sending the request
     */
    async getOrCreateStripeCustomerRequestOpts(requestParameters: GetOrCreateStripeCustomerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['stripeCustomerRequest'] == null) {
            throw new runtime.RequiredError(
                'stripeCustomerRequest',
                'Required parameter "stripeCustomerRequest" was null or undefined when calling getOrCreateStripeCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/payment/stripe-customer`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StripeCustomerRequestToJSON(requestParameters['stripeCustomerRequest']),
        };
    }

    /**
     * Get or create a Stripe customer
     */
    async getOrCreateStripeCustomerRaw(requestParameters: GetOrCreateStripeCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StripeCustomerResponse>> {
        const requestOptions = await this.getOrCreateStripeCustomerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StripeCustomerResponseFromJSON(jsonValue));
    }

    /**
     * Get or create a Stripe customer
     */
    async getOrCreateStripeCustomer(requestParameters: GetOrCreateStripeCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StripeCustomerResponse> {
        const response = await this.getOrCreateStripeCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProviders without sending the request
     */
    async listProvidersRequestOpts(requestParameters: ListProvidersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['entityId'] == null) {
            throw new runtime.RequiredError(
                'entityId',
                'Required parameter "entityId" was null or undefined when calling listProviders().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['entityId'] != null) {
            queryParameters['entity_id'] = requestParameters['entityId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/payment/providers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List payment providers by entity ID
     */
    async listProvidersRaw(requestParameters: ListProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProviderListResponse>> {
        const requestOptions = await this.listProvidersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProviderListResponseFromJSON(jsonValue));
    }

    /**
     * List payment providers by entity ID
     */
    async listProviders(requestParameters: ListProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProviderListResponse> {
        const response = await this.listProvidersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
